### ISSUE TITLE
Convert output of raw2flif back to raw formats

### ISSUE THREAD

**Issue by jonsneyers** [FLIF-hub/FLIF#100]
So, in the last commit I added a script to convert raw camera formats to FLIF. Now I need some help: how to convert this back to some format that can be read by standard tools like `dcraw`?

**Comment by psykauze** [comment]
I don't think there is such a tool like this. A RAW (NEF, DNG, etc...) format embed a lot of necessary data other than the image itself (like the matrix pattern).
If such a tool exist, it would take lot and lot parameters. (I'm still looking for a reversible tool)

I think you could use libtiff to make a DNG (it's a freely available TIFF6.0 format) with the metadata you get from dcraw. Also, for starting, I think it's better to limit RAW inputs (and outputs) to DNG files (Adobe DNG Converter can convert lot of RAW to DNG).

**Comment by jonsneyers** [comment]
This is essentially a duplicate of #111, so closing this one.
