### ISSUE TITLE
maniac/symbol.h Assertion `value>=min' failed.

### ISSUE THREAD

**Issue by matthiaskrgr** [FLIF-hub/FLIF#105]
Trying to convert this image to flif:
https://raw.githubusercontent.com/xbmc/xbmc/master/addons/skin.confluence/media/ScrollBarNib.png
fails:
````
flif: /home/matthias/vcs/github/FLIF/transform/../maniac/symbol.h:245: void writer(SymbolCoder&, int, int, int) [with int bits = 24; SymbolCoder = SimpleSymbolBitCoder<SimpleBitChance, RacOutput24<FileIO>, 24>]: Assertion `value>=min' failed.
````

**Comment by jonsneyers** [comment]
Interesting border case example -- that image is just fully transparent, which messed up the BND computation (which is ignoring all fully transparent pixels, leaving the RGB/YIQ channels with bogus bounds)
