### ISSUE TITLE
Compare to JPEG-XR

### ISSUE THREAD

**Issue by karlcz** [FLIF-hub/FLIF#11]
Your website with the encoding bake-off might benefit from a comparison to JPEG-XR as it is a lot better than JPEG-2000...

**Comment by jonsneyers** [comment]
Added JXR to the list of formats in the comparison.
See https://github.com/FLIF-hub/benchmarks

I can't seem to find a way to let JxrEncApp take RGBA input, can the JXR fans help me with this? It only takes BMP, TIF and PNM input without alpha plane...
