### ISSUE TITLE
Host flif.info on github

### ISSUE THREAD

**Issue by waldyrious** [FLIF-hub/FLIF#115]
Using [Github Pages](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/). Either on this repository (under a gh-pages branch) or in a dedicated repository under the FLIF-hub organization.

**Comment by jonsneyers** [comment]
OK, I copied everything from the original site over here:
https://github.com/FLIF-hub/FLIF-hub.github.io

and I hope everything is configured correctly to make sure that flif.info is actually hosted there now. It takes a while for DNS stuff to propagate.

**Comment by waldyrious** [comment]
kudos for being the fastest / most responsive maintainer I've come across in my 5 years of regular use of github :)

**Comment by ApfelUser** [comment]
Yeah, you're indeed the fastest maintainer I have ever seen, which is really awesome!
