### ISSUE TITLE
support greyscale data

### ISSUE THREAD

**Issue by sharkodlak** [FLIF-hub/FLIF#116]
I'm using e-book reader to browse web and it will be usefull if browser will save some data to do not download colors informations, just greyscale part of image.

**Comment by jonsneyers** [comment]
What exactly do you mean? Greyscale images are already supported, and for color images, the greyscale data gets encoded before the chroma channels (to some extent), so if you're using progressive decoding, it is easy for a browser to avoid downloading (most of) the chroma data.

**Comment by sharkodlak** [comment]
ok, that's great that browser can avoid most of chroma data. I think you can mention it in documentation, because I didn't know about it.

**Comment by jonsneyers** [comment]
Well, browsers _could_ *theoretically* do that, of course none of them natively support FLIF yet, let alone do that kind of clever tricks -- they might not even know they're rendering for a greyscale device, for all I know.
