### ISSUE TITLE
flif-enc.cpp:454:33: unsigned integer overflow

### ISSUE THREAD

**Issue by matthiaskrgr** [FLIF-hub/FLIF#122]
compiled with clang++ and -fsanitize=address,undefined,unsigned-integer-overflow,integer
````
./flif tools/kodim01.png out.flif
flif-enc.cpp:454:33: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned long'
````

**Comment by jonsneyers** [comment]
Oh, interesting, never considered that it would compute 0-1 with unsigned ints before assigning it to the signed int...
