### ISSUE TITLE
Redundant condition

### ISSUE THREAD

**Issue by maddin200** [FLIF-hub/FLIF#132]
extern\stb_image.h line 4096

if (req_comp && req_comp >= 3) // we can directly decode 3 or 4

req_copm always true with req_comp >= 3

**Comment by matthiaskrgr** [comment]
cppcheck also detected this:
````
[extern/stb_image.h:4691]: (style) Redundant condition: If 'req_comp >= 3', the comparison 'req_comp' is always true.
````

(Here is a list of all cppcheck(-git)  findings, if someone wants to have a look (there might be false positives though) https://gist.github.com/matthiaskrgr/b834afa33b6275ddde71 )

**Comment by maddin200** [comment]
Am 31.10.2015 um 02:02 schrieb Matthias Krüger:
>
> cppcheck also detected this:
>
> |[extern/stb_image.h:4691]: (style) Redundant condition: If 'req_comp 
> >= 3', the comparison 'req_comp' is always true. |
>
> (Here is a list of all cppcheck(-git) findings, if someone wants to 
> have a look (there might be false positives though) 
> https://gist.github.com/matthiaskrgr/b834afa33b6275ddde71 )
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FLIF-hub/FLIF/issues/132#issuecomment-152682004>.
>
I also used cppcheck I was not aware it is already in use of the full repo.

Bye Martin
