### ISSUE TITLE
Out of order zoomlevels and zoom level headers

### ISSUE THREAD

**Issue by hrj** [FLIF-hub/FLIF#136]
As discussed on chat, it might be good to have:
* The possibility of out-of-order zoom levels (with some restrictions, such as finer grained zoom level of a channel always comes after the coarser grained level of that channel).
* A header for each level. This header could, for example, have a flag to indicate an all-zero level.

**Comment by hrj** [comment]
Might be related to https://github.com/FLIF-hub/FLIF/issues/135

**Comment by jonsneyers** [comment]
Going to postpone this to M2 for now, but will add a bit in the header to indicate that the default zoomlevel order is used. Later custom zoomlevel orders can be added, but for now, the encoder and decoder will only use/accept the default order.

**Comment by jonsneyers** [comment]
This is possible now, after this commit:
https://github.com/FLIF-hub/FLIF/commit/558a49ecb7288fbdc456af72664b9b4afbc100df

**Comment by jonsneyers** [comment]
(oops, the all-zero header isn't there yet, should it be added?)

**Comment by hrj** [comment]
cool!

About the all-zero header, might be best to check stats on the image-corpus, especially with lossy encoding option.

**Comment by jonsneyers** [comment]
The cost of encoding an entire plane of all-zeroes is quite low, especially with `-X1`. Something like 0.0005 bits per pixel, so a few dozen bytes for the largest plane of a 1 megapixel image. For lossy encoding, I don't think it would help much to handle this as a special case -- it would trim off maybe a few hundred bytes if you force complete subsampling on zoomlevels 0 and 1.

**Comment by jonsneyers** [comment]
Oh and with out-of-order zoomlevels, you can of course just encode all zoomlevels you want to encode, and then terminate the file. Then the remaining zoomlevels get interpolated anyway.
