### ISSUE TITLE
use 2 compression levels (fast_but_worse_compression and original one)

### ISSUE THREAD

**Issue by StephanBusch** [FLIF-hub/FLIF#150]
I would love to see 2 compression levels in FLIF:

one with fast_but_worse_compression
and one with the stronger original one (with the hint of slower decoding)

**Comment by jonsneyers** [comment]
We can do that, and even more than 2 levels, but there is one big disadvantage: it complicates the decoder implementation quite a bit. It would mean that the size of the executable or library would roughly double (perhaps even worse), and also the size of the JavaScript decoder would be significantly larger.
Also, the speed of decoding would be less predictable.

So I think it's better to define FLIF as having just one compression level, one that should obtain a good trade-off between decode speed and compression density, so the decoder can be kept as simple and light-weight as possible.

Nothing stops us from also defining a more complicated file format which gives you more control over that trade-off between speed and compression. Or a variant file format that aims at a different trade-off. For most practical purposes, fast decoding will be important though.

**Comment by sipa** [comment]
Agree.
