### ISSUE TITLE
WebP lossless improved in grayscale encoding in June 2015

### ISSUE THREAD

**Issue by jyrkialakuijala** [FLIF-hub/FLIF#16]
I improved the WebP lossless encoding significantly in June 2015. Using a newer version improves on the faces corpus by 31 % and less on other 4 corpora (0.8, 1.0, 13 and 21 %) I tested from your 26 test corpora. Please consider rerunning WebP lossless compression density tests with the development version from github.

https://github.com/webmproject/libwebp/

**Comment by jonsneyers** [comment]
I modified the overview spreadsheet with the numbers you gave. I'll re-run the tests later.
Do you know the current status of lossless WebP and progressive decoding?

**Comment by jonsneyers** [comment]
I'll be using both the "stable" and the "development" versions of WebP in the benchmarks I'm running now:
https://github.com/FLIF-hub/benchmarks
