### ISSUE TITLE
Channels sorting before YIQ transform

### ISSUE THREAD

**Issue by psykauze** [FLIF-hub/FLIF#163]
#This affect bitstream (maybe 1 byte more in header)
I understand why changing channel order can affect the compressibility. According to this code:
> int Y = ((Pl1 + Pl3) / 2 + Pl2) / 2;  // Replacing R by Pl1, G by Pl2 and B by Pl3
> int I = Pl1 - Pl3 + par*4 - 1;
> int Q = (Pl1 + Pl3) / 2 - Pl2 + par*4 - 1;

"I" is the difference between R & B only, so if the encoder choose the 2 channels (of 3 or 4 channels) with the less difference (-metric  MAE ?) this should improve compression. Also, I think Pl1 channel must have an average value bigger than Pl3 channel.

If this "channel sorting" method is implemented, maybe you could apply it also for 4 planes (like RGGB raw). With RGGB sorting, no need to detect the CFA pattern before reading *.rggb files)

**Comment by psykauze** [comment]
Also, difference analysis between channels could detect (with a threshold?) if it's better to fallback to RGB mode.

**Comment by jonsneyers** [comment]
This could be a good idea indeed, and the overhead (1 byte or so) is certainly not an issue.

However, note that the YIQ transform serves two purposes:
1. improve compression by decorrelating the R G B channels
2. improve progressive decoding by giving priority to luma over chroma, and 'important' chroma (I) over 'less important' chroma (Q).

Changing the channel order can help for 1), but at the cost of losing 2). E.g. if Y is giving weights (0.25, 0.5, 0.25) to (R,G,B) as it is now, it approximates perceptual luminosity reasonably well. If it would give weights (0.25, 0.25, 0.5) it would be a much worse approximation of actual luminosity.

Also, "less difference" does not necessarily mean "better compression". It's the entropy that counts.

On the other hand, for RGGB images, which typically give G a bigger range, one could argue that the perceptual meaning of the YIQ transform is mostly lost anyway, and R&B will tend to be the two channels with minimal difference anyway so the reordering would mostly be CFA pattern detection.

So yes, worth trying. It can be implemented as an optional new transform, or perhaps it could be integrated into PLC.

**Comment by psykauze** [comment]
Yes, I understand the YIQ purpose for progressive decoding. And I know that R and B is "usualy" the planes who as less differences. That's why FLIF is good for both compression and progressive decoding.

1) Maybe a new transform should be made instead of hacking [YIQ]. So RGGB (or anything 2*2 CFA), could fallback to this new transform and let other RGB(A) files with [YIQ]. (Flif can also go back to the RGGB RG1B-G2 decoding for having kind of progressive decoding too by not showing alpha channel in decoder)
2) I've made some test by comparing channels with PSNR and I've got some good results but I don't think it's the better way to measure entropy.
3) The new transform method could be associated with the non-interlaced parameter.

**Comment by jonsneyers** [comment]
Actually, alpha values are encoded before anything else, so if we use the order
G1 G2 B R
then the actual order, with YIQ, would be: R, then 'luma' based on G2+(G1+B)/2, then 'chroma I' based on G1-B, then 'chroma Q', where the I and Q are subsampled relative to A and Y (which would be R and 75% G). That would be very much ok for progressive loading / previewing I think.

**Comment by psykauze** [comment]
So, are you meaning that the progressive decoder should detect the RGGB-flifed file as other kind of format (not like an RGB-A)?

Also, the G1G2B-R was initialy used because I wasn't aware of the real YIQ calculation. My initial purpose is to group the most similar channels (for outside environment) together for YIQ transform but I didn't know why the order of G1, G2 & B could change anything.

After understanding the YIQ transform, I think the G1BG2-R should be better (still for outside environment) because: "I" = G1-G2 and "Q" = Mean(G1,G2) - B

If the decoder order is R, Y, I, Q, so, progressive decoding will show red-ish preview, magenta-ish preview, still magenta but a little more yellow-ish and finally correct color.

(Also, there isn't big interest to preview a RGGB file as RGB without the gamma and color correction factor included in RAW metadata but when metadatas will be implemented, previewing it can be helpful for photographs before "photography processing")

**Comment by psykauze** [comment]
Here a proposal of algorithm for Multi-channel compression: (Let's call it MDL, based on YIQ but without weighting channels)
1) Test similarity only between R&B. <If "MDL transform" is not set and R&B similarity is higher than YIQthreshold, apply YIQ transform, else, fallback to RGB mode. Break.>
2) Test similarities and average value between all channels. If no channels have similarity higher than MDLthreshold but R&B similarity is higher than YIQthreshold fallback to YIQ transform or RGB method if R&B similarity is lower than YIQthreshold.
3) Take the 2 most similar channels (the one that have the higher average value should be first), take the third most similar channel, apply MDL transform. Store the channel order (like 0x01 0x00 0x03 for G,R,A for MDL transform)
4) Test the new MDL channels similarities with all other channels. If at least 2 channels have similarity higher than threshold, go back to 3).

**Comment by jonsneyers** [comment]
Sounds interesting. I'm assigning this to M2 since this can be implemented as a new transform, with impact on forwards compatibility but not on backwards compatibility.

**Comment by jonsneyers** [comment]
Channel reordering is implemented now, so I think this one can be closed. There's still the question of how to determine the best color transform; testing similarity between channels as suggested above might be a good approach. We can discuss this further in #258.
