### ISSUE TITLE
flif generates invalid tree 

### ISSUE THREAD

**Issue by matthiaskrgr** [FLIF-hub/FLIF#166]
trying to convert and then display PSF-line-drawings/1971_San_Jose_Scale_Scales_on_Branch.png fails:

````
/flif ../FLIF_benchmarks/test_images/PSF-line-drawing/1971_San_Jose_Scale_Scales_on_Branch.png out.flif
LD_LIBRARY_PATH=. ./viewflif out.flif
Decoding...
Invalid tree. Aborting tree decoding.
````

**Comment by jonsneyers** [comment]
Thanks for discovering this bug! I also noticed the problem a few hours ago, and I had already fixed it (in case you are wondering how the hell I fixed this _that_ quickly ;)).

Adding `-A` made the default behavior buggy in combination with PLA, and I didn't really test the default behavior when I added `-A`.
