### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [FLIF-hub/FLIF#19]
I've successfully compiled your code on Windows with the following changes: https://github.com/Bulat-Ziganshin/FLIF/commit/17e146da0f5f658f206936dd6fe9a1b2bbd17d27?diff=unified

Note that code for external formats (png, pam) is already using "rb"/"wb" fopen modes.

**Comment by freddyherzog** [comment]
I was about to file the same diff. Well done :)

**Comment by waldyrious** [comment]
Why not submit this as a PR?

**Comment by stinos** [comment]
Can you state compiler and version used please?

**Comment by Bulat-Ziganshin** [comment]
@stinos gcc 4.9.2 32-bit
