### ISSUE TITLE
Add animation to travis test set

### ISSUE THREAD

**Issue by jonsneyers** [FLIF-hub/FLIF#191]
... to avoid bugs like #190

**Comment by matthiaskrgr** [comment]
Hmm, we could have a set of same-sized pngs, convert these into a flif animation, then convert the flif animation back to separate pngs (does flif support that already?) and finally compare source-pngs with the pngs decoded from the flif-animation via "compare -metric AE" , would that work?

**Comment by jonsneyers** [comment]
The benchmark repo already has a script for that...

**Comment by hrj** [comment]
I think the tests should include about a dozen different images + animations, and exhaustive combinations of all the major FLIF options.

It also needs to test the above with truncated input, though I am not very sure how to check for correctness. Atleast, a check to completion could be included.

**Comment by hrj** [comment]
More thoughts:

* The tests should probably be run with `flif.dbg` because it includes assertions.
* The maximum run-time for a Travis-CI build is about 45minutes.
