### ISSUE TITLE
exit() in dynamic libraries

### ISSUE THREAD

**Issue by luigino** [FLIF-hub/FLIF#195]
Perhaps a false positive and perhaps too early to complain about style, but rpmlint is reporting it:

FLIF-libs.x86_64: W: shared-lib-calls-exit /usr/lib64/libflif_dec.so.0 exit@GLIBC_2.2.5
FLIF-libs.x86_64: W: shared-lib-calls-exit /usr/lib64/libflif.so.0 exit@GLIBC_2.2.5
This library package calls exit() or _exit(), probably in a non-fork()
context. Doing so from a library is strongly discouraged - when a library
function calls exit(), it prevents the calling program from handling the
error, reporting it to the user, closing files properly, and cleaning up any
state that the program has. It is preferred for the library to return an
actual error code and let the calling program decide how to handle the
situation.

**Comment by jonsneyers** [comment]
Ah right, there may be one or more `exit()`s left. They are only reachable by decoding a maliciously crafted corrupt .flif file, but still, that is a problem...

**Comment by hrj** [comment]
Since this is C++, could you just throw an exception? (Not sure how it would work with plain C apps).

**Comment by jonsneyers** [comment]
Yes, throwing an exception is an option, but it would have to be caught before returning from the library call.
