### ISSUE TITLE
animation: can't convert same-sized images with differing amount of channels.

### ISSUE THREAD

**Issue by matthiaskrgr** [FLIF-hub/FLIF#203]
I was trying to convert all the images in this directory: https://github.com/wesnoth/wesnoth/tree/master/data/core/images/portraits/humans/ (skipping the "transparent" folder) to a animated flif.

Flif threw an error saying that the dimensions were not the same, however all images were 205 x 205 px.

````
Dimensions of all input images should be the same!
  First image is 205x205, 4 channels.
  This image is 205x205, 3 channels: /home/matthias/vcs/github/wesnoth/data/core/images/portraits/humans/spearman.png
````
only the channels differed. I don't think that differing channels should be that much of an issue...?

**Comment by jonsneyers** [comment]
Well it could upgrade all images to RGBA (adding channels to turn gray into RGB and RGB into opaque RGBA), it's just currently not doing that, while the algorithm does expect all frames to have the same number of channels.
