### ISSUE TITLE
1-pixel file: "rendering at quality=200.00%"; file corrupted

### ISSUE THREAD

**Issue by matthiaskrgr** [FLIF-hub/FLIF#205]
I created a 1-pixel (1x1) image via gimp (150 bytes) and converted it to flif (15 bytes).
````
./src/flif.asan  -i  /tmp/1px.png 1pxtest.flif
````
Now when displaying this with viewflif, viewflif says
````
Decoding progressively...
File ended prematurely or decoding was interrupted.  // I didn't interrupt it, maybe another bug?
15 bytes read, rendering at quality=200.00%
````

EDIT: it seems I also cannot convert the 1px flif back into png:
````
File ended prematurely or decoding was interrupted.
````

**Comment by matthiaskrgr** [comment]
Hm, there seems to be no kind of problems with this image though:
https://github.com/mathiasbynens/small/blob/master/png-transparent.png

**Comment by matthiaskrgr** [comment]
![1px](https://cloud.githubusercontent.com/assets/476013/11758743/2977dbe6-a06f-11e5-8747-da735d8767e1.png) 1px png that I generated using gimp.

**Comment by shaggytwodope** [comment]
Might help someone to figure out the issue that this does not occur on 32bit systems, only seeing this on 64bit. (linux that is)

**Comment by jonsneyers** [comment]
Looks like an off-by-one error in the pixel counting, which makes it think it has decoded 2 pixels, which is more than the 1 pixel it should decode at quality target 100%, so it enters the code path which is normally only entered when decoding at a lower quality. Debugging...
