### ISSUE TITLE
Lossiness detected!

### ISSUE THREAD

**Issue by goblin** [FLIF-hub/FLIF#210]
I've found several cases where FLIF appears to be losing data after compression/decompression.

I'm working on a RAW compressor, and I've decided to put the second green pixel from a Bayer sensor into the alpha channel of a 16-bit PNG. Out of about 400 RAW files, about 50 of them have a discrepancy. I've tested the first one and it seems it's due to FLIF losing some data.

Attached is a cropped 32x32 tile from a photo that caused the problem. It appears the tile itself also causes a very similar lossiness problem (although the exact broken bits are just a tiny bit different). I can provide more such samples if needed.

How to reproduce:

1. Save the sample square (below) as cropped.png
2. `flif -e cropped.png cropped.png.flif`
3. `flif -d cropped.png.flif cropped.png.flif.png`
4. `mkfifo fi1 fi2`
5. `convert cropped.png -depth 16 rgba:- | xxd > fi1 &`
6. `convert cropped.png.flif.png -depth 16 rgba:- | xxd > fi2 &`
7. `diff -u fi1 fi2` results in:
```
@@ -57,7 +57,7 @@
 0000380: c024 8024 4021 8022 4024 4026 c020 8024  .$.$@!."@$@&. .$
 0000390: 8021 0023 c022 8023 4024 4023 4020 0024  .!.#.".#@$@#@ .$
 00003a0: c022 0023 c021 0024 4023 c023 c020 8023  .".#.!.$@#.#. .#
-00003b0: 0023 4024 c020 8026 0023 4023 0021 0000  .#@$. .&.#@#.!..
+00003b0: 0023 4024 c020 8026 c023 0023 8021 0000  .#@$. .&.#.#.!..
 00003c0: 8022 0023 4023 8024 8022 c022 4021 0024  .".#@#.$."."@!.$
 00003d0: 8024 8024 c022 0024 4024 8022 4021 8025  .$.$.".$@$."@!.%
 00003e0: 4024 c022 c020 0022 c022 8025 0021 0024  @$.". .".".%.!.$
```

Tested on an amd64 Debian jessie machine at current git master ( 090d969812b016a21b54c0a0015c23a9f191ab86 ). Gcc 4.9.2-10. Can provide more details / samples if needed.

Here's the sample:
![cropped](https://cloud.githubusercontent.com/assets/2834/12177392/cbab908e-b563-11e5-98a0-8eb66056b871.png)

**Comment by goblin** [comment]
Hmm, the last word in that line, which should be the Alpha channel, has value `0000`, indicating that the pixel is probably transparent as hell. So RGB values shouldn't really matter when displaying that particular png... But I wonder what the actual behaviour should be here? A guess is that FLIF should preserve those RGB values anyway..? But if you think it shouldn't, then please feel free to close the issue.

**Comment by jonsneyers** [comment]
See https://github.com/FLIF-hub/FLIF/tree/master/raw-tools for some scripts related to raw compression. You can use `raw2rggb` to create a `.rggb` file, which is a Bayer mosaic'ed .pgm file as outputted by `dcraw -E -4`. FLIF can read and write such files.

The RGB values at A=0 are lossy by default. To disable that behavior and have also the invisible RGB values stored losslessly, use the option `--keep-invisible-rgb` (abbreviated as `-K`). This option is enabled implicitly when you use `.rggb` files as input (because the fourth channel is a color channel, not an alpha channel).

**Comment by goblin** [comment]
Awesome, thanks! :-)
