### ISSUE TITLE
Output full black for fully transparent pixels

### ISSUE THREAD

**Issue by orlp** [FLIF-hub/FLIF#213]
As we discussed in gitter, we should probably be consistent to the outer world, and replace any fully transparent pixels with black R, G, B values. E.g.:

    if (a == 0) r = g = b = 0;

If we do this before computing the checksum in the encoder as well, we can run the checksum on the RGBA values rather than the internal values. This makes it possible for generic tools to verify checksums on decoded FLIF images.

**Comment by jonsneyers** [comment]
One added advantage of computing the checksum on the RGBA values is that it makes it easier to verify that transformations themselves are correct.
