### ISSUE TITLE
Reverse sign to match YCoCg, and properly name the color space

### ISSUE THREAD

**Issue by orlp** [FLIF-hub/FLIF#215]
Currently the internal algorithm uses a non-standard colorspace, which is close to YCoCg, but with a channel flipped in sign, and a subtraction. I've made a pull request that properly explains standard YCoCg.

We should change the internal color space to standard YCoCg for easier explanation, logic and consistency, and we should rename the incorrectly named "YIQ" to the correct "YCoCg".

**Comment by sipa** [comment]
Agree.
