### ISSUE TITLE
Make from outside src is not parallel

### ISSUE THREAD

**Issue by est31** [FLIF-hub/FLIF#225]
When you try to run make from the main directory, you get:
```
$ make -j 4
cd src; make
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```

I guess the issue is that the sub-make is not not properly started in the main Makefile. The docs to explain how to do it properly: https://www.gnu.org/software/make/manual/html_node/Recursion.html

There is a workaround by doing cd src before running make.

**Comment by jonsneyers** [comment]
Thanks!
