### ISSUE TITLE
Error compiling on OS X (primarily involving endianness macros)

### ISSUE THREAD

**Issue by LRFLEW** [FLIF-hub/FLIF#233]
So I was attempting to build this from source, and ran into a compile error when using make:

```
image/image.hpp:328:29: error: invalid range expression of type
      'unsigned char *'; no viable 'begin' function available
            for (pixel_t& x : data) x = swap16(x);
```

This was repeated multiple times, and included line number 328 and 337. This is likely an issue that should be resoled for big-endian machines (what little exist still), but as it turns out, this wasn't the core issue with the build.

The code was assuming that there would be `__BIG_ENDIAN` `__LITTLE_ENDIAN` and `__BYTE_ORDER` macros in the context which weren't there. From what I can tell, OS X doesn't use the double-underscore for these macros. Adding the following lines to `config.h` allowed it to build:

```
#include <machine/endian.h>
#define __BIG_ENDIAN BIG_ENDIAN
#define __LITTLE_ENDIAN LITTLE_ENDIAN
#define __BYTE_ORDER BYTE_ORDER
```

This should probably be implemented in a more platform-independent way for the project, though.

**Comment by jonsneyers** [comment]
Should be fixed with https://github.com/FLIF-hub/FLIF/commit/9868c0e2a8df71749121e5df5dfdd4c996dd08c7
