### ISSUE TITLE
flifcrush does not work

### ISSUE THREAD

**Issue by StephanBusch** [FLIF-hub/FLIF#244]
After having installed Python 3.5.1 for Win x64 and opening main.py in Python Shell
and pressing F5 for running that script, an error message appears:

Traceback (most recent call last):
  File "D:\TESTSETS\main.py", line 24, in <module>
    from PIL import Image
ImportError: No module named 'PIL'

Python is installed in C:\Users\SqueezeChart2014\AppData\Local\Programs\Python\Python35
the python file main.py has this in the first line: #!/usr/bin/python3

**Comment by justinclift** [comment]
If you remove the `#!/usr/bin/python3` line, does it work properly? :smile:

**Comment by jonsneyers** [comment]
Looks like you need to install PIL...

**Comment by jonsneyers** [comment]
Closing this issue, please go to https://github.com/matthiaskrgr/flifcrush/issues if you have further questions about flifcrush.
