### ISSUE TITLE
Building on OS X

### ISSUE THREAD

**Issue by bumblebritches57** [FLIF-hub/FLIF#247]
OS X uses the .dylib extension for dynamic libraries.

It'd be nice if you'd use OS X's naming convention on OS X machines.

I'd do it myself, but I'm not all that familiar with makefile syntax.

**Comment by fherzog2** [comment]
Does a CMake build work in this case?

**Comment by bumblebritches57** [comment]
Nope. still .so.0

**Comment by jonsneyers** [comment]
Is it just a matter of changing the extension or is more needed?

**Comment by bumblebritches57** [comment]
Just changing the extension. It's fine otherwise.

**Comment by bumblebritches57** [comment]
@jonsneyers It *almost* works, the only problem is that the .0 is still being appended to the libflif.dylib file name. instead of it being something like libflif.0.dylib
