### ISSUE TITLE
relevant

### ISSUE THREAD

**Issue by r-lyeh** [FLIF-hub/FLIF#250]
https://github.com/yardstickpics/metadata

**Comment by bumblebritches57** [comment]
How is this relevant to anything? this is a perfect example of a terrible "issue" report, kids.

**Comment by sipa** [comment]
It looks like an extensive set of lossless test images. Very relevant indeed, thanks!

**Comment by jonsneyers** [comment]
Thanks for the link, I already knew about the project from Kornel, it's very relevant indeed.

Mostly relevant for https://github.com/FLIF-hub/benchmarks though. Closing the issue.
