### ISSUE TITLE
Failure on all-black images

### ISSUE THREAD

**Issue by kenta2** [FLIF-hub/FLIF#271]
ppmmake black 5000 2 > black1.ppm
flif -e black1.ppm black1.flif
flif -d black1.flif black1.flif.ppm
 
CORRUPTION DETECTED: checksums don't match (computed: 45862d4b v/s read: 4fffffff)! (partial file?) 
 
Error seems to occur at 10000 pixels.  A 4999x2 black image works fine.

**Comment by jonsneyers** [comment]
Thanks for finding and reporting this decode bug!
