### ISSUE TITLE
fewer dependencies for viewflif ?

### ISSUE THREAD

**Issue by hrj** [FLIF-hub/FLIF#274]
Currently, `viewflif` depends on `libsdl2`, so to build it on a minimal Ubuntu box, `apt-get install libsdl2-dev` gives:

```
The following NEW packages will be installed:
  libasound2-dev libasyncns0 libavahi-client-dev libavahi-common-dev
  libboost-system1.54.0 libdbus-1-dev libdrm-amdgpu1 libdrm-dev libegl1-mesa
  libegl1-mesa-dev libegl1-mesa-drivers libelfg0 libflac8 libgbm1
  libgl1-mesa-dev libgles2-mesa libgles2-mesa-dev libglib2.0-bin
  libglib2.0-dev libglu1-mesa libglu1-mesa-dev libice-dev libmirclient-dev
  libmirclient7 libmirclientplatform-mesa libmirprotobuf-dev libmirprotobuf0
  libopenvg1-mesa libpcre3-dev libpcrecpp0 libprotobuf-dev libprotobuf-lite8
  libprotobuf8 libpthread-stubs0-dev libpulse-dev libpulse-mainloop-glib0
  libpulse0 libsdl2-2.0-0 libsdl2-dev libsm-dev libsndfile1 libts-0.0-0
  libts-dev libudev-dev libvorbisenc2 libwayland-client0 libwayland-cursor0
  libwayland-dev libwayland-egl1-mesa libwayland-server0 libx11-dev libx11-doc
  libx11-xcb-dev libxau-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev
  libxcb-present-dev libxcb-randr0 libxcb-randr0-dev libxcb-render0-dev
  libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0 libxcb-xfixes0-dev
  libxcb1-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev
  libxfixes-dev libxi-dev libxinerama-dev libxkbcommon-dev libxkbcommon0
  libxrandr-dev libxrender-dev libxshmfence-dev libxss-dev libxt-dev libxv-dev
  libxxf86vm-dev mesa-common-dev mircommon-dev tsconf x11proto-core-dev
  x11proto-damage-dev x11proto-dri2-dev x11proto-fixes-dev x11proto-gl-dev
  x11proto-input-dev x11proto-kb-dev x11proto-randr-dev x11proto-render-dev
  x11proto-scrnsaver-dev x11proto-video-dev x11proto-xext-dev
  x11proto-xf86vidmode-dev x11proto-xinerama-dev xorg-sgml-doctools xtrans-dev
```

I just did a quick search for alternatives to libSDL and found [SFML](http://www.sfml-dev.org/). Dependencies seem to be fewer:

```
sudo apt-get install libsfml-dev
The following NEW packages will be installed:
  libasyncns0 libdrm-amdgpu1 libdrm-dev libflac8 libgl1-mesa-dev libglew1.10
  libglu1-mesa libglu1-mesa-dev libopenal-data libopenal1
  libpthread-stubs0-dev libpulse0 libsfml-audio2 libsfml-dev libsfml-graphics2
  libsfml-network2 libsfml-system2 libsfml-window2 libsndfile1 libvorbisenc2
  libx11-dev libx11-doc libx11-xcb-dev libxau-dev libxcb-dri2-0-dev
  libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev libxcb-randr0
  libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-sync-dev
  libxcb-xfixes0 libxcb-xfixes0-dev libxcb1-dev libxdamage-dev libxdmcp-dev
  libxext-dev libxfixes-dev libxshmfence-dev libxxf86vm-dev mesa-common-dev
  x11proto-core-dev x11proto-damage-dev x11proto-dri2-dev x11proto-fixes-dev
  x11proto-gl-dev x11proto-input-dev x11proto-kb-dev x11proto-xext-dev
  x11proto-xf86vidmode-dev xorg-sgml-doctools xtrans-dev
```

(I have no experience with SFML, but it seems active and well documented.)

**Comment by jonsneyers** [comment]
At the moment, `viewflif` is not really meant to be part of the main flif package, it's just some example code to document how you can use libflif to decode progressively. So I don't really care too much about the dependencies. But if someone feels like rewriting viewflif using some other GUI framework, feel free to do so (it doesn't hurt to have more than one example).

In practice, I don't think something like `viewflif` should really exist for end-users. I would rather want the main toolkits like GTK, Qt, SDL-image etc to have support FLIF, so it becomes easy for existing picture viewers written in those frameworks to add FLIF support.

**Comment by jonsneyers** [comment]
Closing the issue.
Note to distro packagers: read the above. Don't include `viewflif` in a flif and/or libflif package, since it does indeed bring in unnecessary dependencies. Also it's a very stupid/unpolished viewer; there is no reason for it to be in your distribution!

**Comment by lehitoskin** [comment]
The Makefile still builds `viewflif` by default, which isn't too bad since you can specify what things you want to make, but it also installs `viewflif` by default, which you cannot work around. To do that the Makefile would need to be changed or packagers would need to call `install` manually, which is icky.

**Comment by jonsneyers** [comment]
Good point. Changed the Makefile to not build and not install `viewflif` by default.

**Comment by shaggytwodope** [comment]
@jonsneyers Would you be able to make a note of this next time a release is tagged?

**Comment by jonsneyers** [comment]
Sure!
