### ISSUE TITLE
viewflif renders images as all white when using nvidia gpu

### ISSUE THREAD

**Issue by ghost** [FLIF-hub/FLIF#278]
I can switch between my Intel HD Graphics 530 and Nvidia GTX 970M. When using the Intel GPU the images from viewflif can be viewed as expected. When using the Nividia GPU the images are rendered as all white (blank).

**Comment by jonsneyers** [comment]
Weird. Sounds like a bug in SDL2. FLIF or viewflif is not using the GPU directly in any way.

**Comment by jonsneyers** [comment]
Can't really do much, might be a problem in viewflif but seems more likely to be some kind of video driver issue or SDL2 bug.

**Comment by lehitoskin** [comment]
@ghost Are you using GNU/Linux? If so, are you using the proprietary nvidia drivers or nouveau drivers?

**Comment by lehitoskin** [comment]
This appears to be a bug in the proprietary nvidia video drivers.

Gentoo box with proprietary nvidia drivers can't get `viewflif` to work
Fedora box with proprietary nvidia drivers also cannot get `viewflif` to work
Fedora box with Intel card/drivers works
Fedora Live USB using nouveau drivers works
Both Gentoo and Fedora boxes (with proprietary nvidia drivers) can get `viewflif` to work inside virtual machines.
