### ISSUE TITLE
Please compare with Gralic too

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [FLIF-hub/FLIF#28]
How it compares to (closed-source) gralic, flic and qlic? http://imagecompression.info/gralic/
Those codecs are for photograps generally, but nonetheless it would be interesting to compare on different types of images.

here we've found that Gralic compresses 10% better:
http://encode.ru/threads/2321-FLIF-Free-Lossless-Image-Format?p=45075&viewfull=1#post45075

**Comment by jonsneyers** [comment]
I can't test because I don't know where to find gralic, flic and qlic.
Does Gralic support progressive decoding?

**Comment by skymmeroid** [comment]
http://imagecompression.info/gralic/Gralic111d.zip
http://imagecompression.info/gralic/flic21d.zip
http://imagecompression.info/gralic/qlic1d.zip

**Comment by jonsneyers** [comment]
OK, someone else will have to test that. I'm using an ARM chromebook running Debian here.
