### ISSUE TITLE
create 7-Zip plugin

### ISSUE THREAD

**Issue by StephanBusch** [FLIF-hub/FLIF#280]
please create a plugin for 7-Zip so that this open and free archiver can also compress images using FLIF.
This would also help making FLIF more famous in the world.

there are already plugins that work with 7-Zip (including descriptions and sources):

ZSTD

https://github.com/mcmilk/7-Zip-Zstd

LZHAM
http://richg42.blogspot.de/search?updated-max=2015-12-03T16:22:00-08:00&max-results=7&start=21&by-date=false
https://github.com/richgel999/lzham_codec_devel

**Comment by bumblebritches57** [comment]
You'd be lucky if 7z could parse FLIF.

**Comment by jonsneyers** [comment]
Thanks for opening this issue, but I don't think it belongs here. This is a feature request for the 7-Zip project, not for this one.

In general, general-purpose compression methods would benefit from detecting uncompressed or poorly-compressed images (e.g. BMP, raw, or even PNG/GIF) and recompressing them with better methods when creating an archive; they can use flif or libflif for that. Most of the work is in making it fully reversible, which is tricky: you don't just have to preserve the pixels, you also need to be able to get the exact original file back. In many formats, there are many ways to encode the same pixels (e.g. palette reordering, different ways to do the DEFLATE, etc etc), so this is a very difficult/impossible task. E.g. how would you reconstruct a zopflipng-compressed PNG from a FLIF?

Of course, usually it's OK if you just have the pixels, not the exact file. But a general-purpose archiver can't do that: you expect bitwise identical output after a compress/decompress round trip.

So 1) I think this is very nontrivial / impossible, and 2) this is beyond the scope of the FLIF project itself. Closing the issue.
