### ISSUE TITLE
Compressor says "corruption detected" for large images

### ISSUE THREAD

**Issue by kedorlaomer** [FLIF-hub/FLIF#282]
Consider the large image at http://api.ning.com/files/eOkD9SMZvVrdJH0rMYfSv2lJ7TQSEtsN1S5ApfO67HiqGnNi6QI714UF0ApR*eg-jSqtnUt8hoQez4LSucYowcT-APKIWppj/doodlecolorattempt1.jpg or any other large image.

```
$ jpegtopnm doodlecolorattempt1.jpg > doodlecolorattempt1.pnm
$ flif -vvvvv -E100 doodlecolorattempt1.pnm doodlecolorattempt1.flif
```

This generates a very small file (a few hundred bytes) that cannot be decoded. Additionally, it shows the error message `Corruption detected!`.

Note: I thought this might be caused by a compiler bug. `g++ --version` says

```
    g++ (Debian 4.9.2-10) 4.9.2
```

on i686. I tried recompiling without optimizations (`-O0`); additionally, I tried compiling on an ARM7 where `g++ --version` says

```
    g++ (Debian 5.4.0-6) 5.4.0 20160609
```

— The behaviour doesn't change. (I couldn't try clang.)

I'm using the commit `e2a523f45ed811a4975477cbd7ff30acd9190dfa` of flif.

The error message stems from src/transform/colorbuckets.hpp, line 296.

**Comment by jonsneyers** [comment]
I cannot reproduce this bug. A very small file seems to indicate that something goes wrong at encode time -- maybe some memory allocation failure that isn't caught? Is it producing the small file relatively quickly, or does it take a long time?

Encoding large images with -E100 takes an annoyingly long time; do you still get the same problem with -R0 instead of -E100?

I'm assuming that the issue is an uncaught memory allocation error somewhere in ColorBuckets.

**Comment by jonsneyers** [comment]
Thanks for reporting the bug!

I still cannot reproduce the problem. Here are some questions that might help to find out what's going on:

Does the error message (`Corruption detected!`) appear while encoding, or when trying to decode the problematic file?

Can you paste the output of the encoder? Feel free to add some more `-vvvvvvv` to make it as verbose as possible.

Can you try `make flif.dbg` and use the resulting debug executable `flif.dbg`, to see if any `assert`s are triggered?

**Comment by kedorlaomer** [comment]
`flif.dbg` with `-E0` dies with the error

         flif.dbg: flif-enc.cpp:250: void flif_encode_FLIF2_inner(IO&, Rac&, std::vector<Coder>&, const Images&, const ColorRanges*, int, int, const int*) [with IO = FileIO; Rac = RacOutput24<FileIO>; Coder = FinalPropertySymbolCoder<SimpleBitChance, RacOutput24<FileIO>, 10>; Images = std::vector<Image>]: Assertion `curr >= min' failed.

without producing an output file. With `-E100`, the same error `Corruption detected!` appears; the encoder doesn't die. When trying to `viewflif` this file, the *viewer* dies with the message:

        Decoding progressively...
        Corruption detected!
        [...]
        Corruption detected!
        Invalid tree. Aborting tree decoding.
        File probably truncated in the middle of MANIAC tree representation. Interpolating.
        23125 bytes read, rendering at quality=0.39%
        Closed

I'm somewhat astonished that the file is 165M.

The encoder `flif` with `-E0` produces a huge file (200M), on which `viewflif` barks:

        Decoding progressively...
        Invalid tree. Aborting tree decoding.
        File probably truncated in the middle of MANIAC tree representation. Interpolating.
        1534 bytes read, rendering at quality=0.39%
        Closed

Github doesn't want to let me attach these files. I assume only the first few hundred bytes are interesting. Should I attach a hexdump?

**Comment by jonsneyers** [comment]
Still can't reproduce. Can anyone else reproduce this?

**Comment by kedorlaomer** [comment]
Which part can't you reproduce? The `Corruption detected` or the production of unreadable image files? Or none?

**Comment by lehitoskin** [comment]
Encoding the PNM to FLIF with `-E100` doesn't fail or bring up any errors, but then `viewflif` brings up a window with a giant white box in the middle, same thing for `-E0`.

The output for `viewflif` looks like this
```
Decoding progressively...
305955 bytes read, rendering at quality=5.51%
458438 bytes read, rendering at quality=19.34%
663043 bytes read, rendering at quality=38.62%
704803 bytes read, rendering at quality=43.82%
Closed
```

I figured it was just taking a long time to load the image, but I left it up for quite some time (at least, much longer than any sane program should take to load an image) and it was still just a plain white box.

**Comment by jonsneyers** [comment]
`viewflif` probably has some bugs, and certainly performance issues.

Can anyone reproduce the issue in `flif` itself?

**Comment by hrj** [comment]
md5sum of pnm file: 8ced2e9b5bfbdc72ae8edd953ad91796

gcc --version : 4.8.4

`flif.dbg` -E0 works fine
`flif -E0` works fine

`flif -E100` was taking too long, so I stopped it after 10 mins.

I have not tried viewflif.
