### ISSUE TITLE
Windows Imaging Component Codec for FLIF

### ISSUE THREAD

**Issue by peirick** [FLIF-hub/FLIF#284]
A WIC Codec for encoding and decoding of FLIF-Files can now be found at: https://github.com/peirick/FlifWICCodec

I had to extend FLIF_IMAGE with the following methods
flif_image_write_row_N
flif_image_read_row_N
Wich reads and writes a row, dependend on the channels, of a FLIF_IMAGE 

I also extended the constructor flif_create_image with an parameter for the number channels to create.

**Comment by fherzog2** [comment]
See also https://github.com/fherzog2/flif_windows_plugin

**Comment by jonsneyers** [comment]
Cool!
Could you perhaps sign the CLA and make a pull request for the necessary changes to libflif? Thanks in advance.

**Comment by peirick** [comment]
How do I sign the CLA? I'm a newbe to github and opensource :) 
I'm not very happy with the changes I made to libflif, so I try to refactore the codec, so I don't need the changes.

**Comment by peirick** [comment]
I've added an Appvoye buildplan, and the changes to import some images for encoding are merged now. Thanks :-) So this can now be closed right?

**Comment by jonsneyers** [comment]
Yes. Thanks!
I first had to do this, before closing this issue: https://github.com/FLIF-hub/FLIF-hub.github.io/commit/f2b1e3ed6ce6b3c514174183fa210eba9e6b81f3
