### ISSUE TITLE
Compile error in image-png.cpp

### ISSUE THREAD

**Issue by bermond** [FLIF-hub/FLIF#288]
I'm getting the following error when trying to compile FLIF:

```
g++ -std=gnu++11 -I/usr/include/libpng16 -DLODEPNG_NO_COMPILE_PNG -DLODEPNG_NO_COMPILE_DISK -DNDEBUG -O2 -ftree-vectorize -flto -fwhole-program -g0 -Wall maniac/chance.cpp maniac/symbol.cpp image/crc32k.cpp image/image.cpp image/image-png.cpp image/image-pnm.cpp image/image-pam.cpp image/image-rggb.cpp image/image-metadata.cpp image/color_range.cpp transform/factory.cpp common.cpp flif-enc.cpp flif-dec.cpp io.cpp ../extern/lodepng.cpp flif.cpp -lpng16 -o flif     
image/image-png.cpp: In function ‘int image_save_png(const char*, const Image&)’:
image/image-png.cpp:369:16: error: invalid conversion from ‘png_bytep {aka unsigned char*}’ to ‘png_charp {aka char*}’ [-fpermissive]
     txt.text = profile;
                ^~~~~~~
make: *** [Makefile:39: flif] Error 1
```

This error was introduced in commits from the last few development days. It was compiling well some few days ago.

Using:
**FLIF:** git master
**OS:** Arch Linux x86_64
**Linux (kernel):** 4.7.2
**GCC:** 6.1.1
**glibc:** 2.24
**libpng:** 1.6.24

**Comment by AmirIHz** [comment]
I have the same problem (on OS X):

`/usr/local/bin/clang++ -std=gnu++11 -I/usr/local/Cellar/zlib/1.2.8/include -I/usr/local/Cellar/libpng/1.6.24/include/libpng16 -DLODEPNG_NO_COMPILE_PNG -DLODEPNG_NO_COMPILE_DISK -DNDEBUG -O2 -ftree-vectorize -g0 -Wall maniac/chance.cpp maniac/symbol.cpp image/crc32k.cpp image/image.cpp image/image-png.cpp image/image-pnm.cpp image/image-pam.cpp image/image-rggb.cpp image/image-metadata.cpp image/color_range.cpp transform/factory.cpp common.cpp flif-enc.cpp flif-dec.cpp io.cpp ../extern/lodepng.cpp flif.cpp -L/usr/local/Cellar/libpng/1.6.24/lib -lpng16 -o flif
/usr/local/bin/clang++ -std=gnu++11 -I/usr/local/Cellar/zlib/1.2.8/include -I/usr/local/Cellar/libpng/1.6.24/include/libpng16 -DLODEPNG_NO_COMPILE_PNG -DLODEPNG_NO_COMPILE_DISK -DNDEBUG -O2 -g0 -Wall -shared -fPIC maniac/chance.cpp maniac/symbol.cpp image/crc32k.cpp image/image.cpp image/image-png.cpp image/image-pnm.cpp image/image-pam.cpp image/image-rggb.cpp image/image-metadata.cpp image/color_range.cpp transform/factory.cpp common.cpp flif-enc.cpp flif-dec.cpp io.cpp ../extern/lodepng.cpp library/flif-interface.cpp -L/usr/local/Cellar/libpng/1.6.24/lib -lpng16 -Wl,-install_name,libflif.dylib.0 -o libflif.dylib.0
image/image-png.cpp:369:14: error: assigning to 'png_charp' (aka 'char *') from incompatible type 'png_bytep' (aka 'unsigned char *')
    txt.text = profile;
             ^ ~~~~~~~
image/image-png.cpp:369:14: error: assigning to 'png_charp' (aka 'char *') from incompatible type 'png_bytep' (aka 'unsigned char *')
    txt.text = profile;
             ^ ~~~~~~~
1 error generated.
1 error generated.
make: *** [Makefile:39: flif] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:53: libflif.dylib] Error 1`

**FLIF:** git master (commit: e570983)
**OS:** OS X El Capitan 10.11.6 (15G31)
**Kernel:** Darwin 15.6.0 (XNU 3248.60.10~1) x86_64
**Clang:** clang version 3.8.1 (tags/RELEASE_381/final 275397)
**libpng:** 1.6.24
**zlib:** 1.2.8

**Comment by jonsneyers** [comment]
I hope it is fixed now...

**Comment by shaggytwodope** [comment]
@jonsneyers Compiles for me on Arch just fine now. Question tho, any plans for tagging a new release? The flif-git package for flif works fine on arch. But the release version is rather dated. I think it's v0.1 if I recall.

**Comment by jonsneyers** [comment]
I think we're almost ready to drop the "rc" and call it a v0.2 release. I would like to do that before Sept 26, when I'll present FLIF at the ICIP 2016 conference.

**Comment by shaggytwodope** [comment]
Well I maintain the aur packages. Love a ping if possible when you tag a release.

**Comment by AmirIHz** [comment]
Compiles fine now. Thanks.

**Comment by bermond** [comment]
Commit [e103f906c593a30cd13f4f45c306c574fcb6da66](https://github.com/FLIF-hub/FLIF/commit/e103f906c593a30cd13f4f45c306c574fcb6da66) fixed compilation error.

Thanks for the support.
