### ISSUE TITLE
Enhancing the API for performance

### ISSUE THREAD

**Issue by fherzog2** [FLIF-hub/FLIF#296]
While working on the windows plugin, I found some cases where the API is still lacking.

First, there could be a function for getting some basic info from a FLIF file without having to decode any images. This could also be used as a quick check if a file is indeed FLIF.

```
FLIF_DLLIMPORT FLIF_INFO* FLIF_API flif_read_info_from_memory(const void* buffer, size_t buffer_size_bytes);

FLIF_DLLIMPORT void FLIF_API flif_destroy_info(FLIF_INFO* info);

FLIF_DLLIMPORT uint32_t FLIF_API flif_info_get_width(FLIF_INFO* info);

FLIF_DLLIMPORT uint32_t FLIF_API flif_info_get_height(FLIF_INFO* info);

FLIF_DLLIMPORT uint8_t  FLIF_API flif_info_get_nb_channels(FLIF_INFO* info);

FLIF_DLLIMPORT uint8_t  FLIF_API flif_info_get_depth(FLIF_INFO* info);
```

Second, for animated FLIF, there could be a parameter to decode just the first image as a preview and skip the rest. Without it, creating a thumbnail from animated FLIF is kinda slow.

```
FLIF_DLLIMPORT void FLIF_API flif_decoder_decode_until_image(FLIF_DECODER* decoder, size_t index);
```

Any thoughts about this?

**Comment by peirick** [comment]
I like that idea

**Comment by peirick** [comment]
Maybe just fill a struct, then we don't need all the getters. Simmilar to what webp does. First field is struct size, so we keep binary compatible if there are more fields coming.

**Comment by fherzog2** [comment]
Opaque structs are safer to use. What does it get you to have public structs? Less typing?

**Comment by peirick** [comment]
Well, I think less functions will make an easier API. You won't forget to call flif_destroy_info. But either will do. I'm OK with opaque structs.

**Comment by jonsneyers** [comment]
I think in this case, a non-opaque struct is probably OK since you'll typically want all or most of the information anyway (you don't want the width but not the height, or the bit depth but not the number of channels).

As for animations: it's impossible to decode just the first frame without decoding the rest of it, because animations are stored with all frames mixed together. This makes it possible to progressively load a full animation at a lower resolution (so you could use a lower res animation as a preview), but it makes it impossible to load just the first frame without also loading all the other frames.

**Comment by fherzog2** [comment]
Seems I'll have to live with slow thumbnails then.

Then I'll just work on the info-API.

**Comment by peirick** [comment]
Should we extend the FLIF_INFO object to contain the metadata blobs? Currently the metadata ist attached to the first image object. Sometimes I only need the metadata... Or ist there another fast way to get that blobs?

**Comment by jonsneyers** [comment]
I suppose the Image::get_metadata and Image::set_metadata functions should get some wrappers in the library API. Probably best to add some checks too, e.g. to disallow adding multiple chunks with the same name (e.g. two color profiles).

**Comment by peirick** [comment]
#298

**Comment by jonsneyers** [comment]
Great, thanks!

**Comment by jonsneyers** [comment]
Can I close this one, or is there still something that needs to be done?

**Comment by peirick** [comment]
Yes, thanks :)
