### ISSUE TITLE
Support to standard input/output

### ISSUE THREAD

**Issue by chezsick** [FLIF-hub/FLIF#299]
hello it's sick, my problem, the program flif, not supporting standard input output same pipe named
this program flif, force the extention, so not supporting temporary file by mktemp command.

without this support, will not clean, if you do imagemagick command.

thank

**Comment by jonsneyers** [comment]
Now `flif - -` will encode stdin (assumed to be ppm) to stdout; `flif -d - -` decodes stdin to stdout.
