### ISSUE TITLE
Argument list too long creating long animations

### ISSUE THREAD

**Issue by gradha** [FLIF-hub/FLIF#300]
Testing creation of animations I fed 9000 images to flif and bash complained about the argument list being too long. Figured out the problem was the expansion was generating full paths for each file so I was able to run the command going into the source directory and running the command there.

Maybe add to the command line options a switch to accept a pattern to glob or process input directories as 'get everything in there'?

**Comment by jonsneyers** [comment]
What would be a good cross-platform way to implement this? Accept filenames that contain printf patterns like %05i and loop over them?

**Comment by lucaswerkmeister** [comment]
I think one common solution is to accept an “option file”, `@filename`, and process its contents as additional options as if they’d been passed on the command line. (Examples: `gcc`, `mkvmerge`)

**Comment by gradha** [comment]
For me it's enough to have directories as allowed input, it's pretty easy to create a directory with hard links to whatever complex filter you can concoct in bash. But if you want to go full pattern typical implementations use [glob](http://linux.die.net/man/3/glob) on POSIX and [FindFirstFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364418(v=vs.85).aspx) on win32. Reading input from a file is preferable as a separate switch.

**Comment by jonsneyers** [comment]
Filenames that contain a % will now be used as a printf-style pattern for both input and output filenames. So e.g. if your filenames are
frame00000.png
frame00001.png
frame00002.png
etc, then you can use `flif frame%05d.png result.flif` to encode them. Gaps in the numbering are tolerated to some extent (e.g. if you don't start with 0, or if you removed all odd frames or something).
