### ISSUE TITLE
Clarification about encoder license

### ISSUE THREAD

**Issue by gradha** [FLIF-hub/FLIF#302]
Reading through the readme the first notice about licenses is:

```
The reference implementation of FLIF is released under the terms of the GNU Lesser General Public License version 3 or later (LGPLv3+).

The decoder library libflif_dec is released under a weaker, non-copyleft free software license: the Apache 2.0 license.
```

As such I understand that the encoder part of the library falls under the LGPLv3+. A little bit later can be read:

```
  * Navigate to the FLIF/src directory and run `make` to compile everything, or
    * `make flif` …
    * `make libflif.so` to build the GPL'ed shared library
```

From this I understand that the ``libflif.so`` shared library containing the encoder part is actually GPL and not LGPL. Or maybe not?

I would like to know the details of this with regards to inclusion of FLIF encoder in a mobile app. While mobile apps support shared linking I understand their strongly controlled environment prevents GPL freedoms for users (aka, users updating the library), so would it be ok to use FLIF in such environments with GPL/LGPL?

**Comment by jonsneyers** [comment]
The encoder is LGPLv3, the decoder is Apache 2.0.
I've updated the readme to reflect that.

If you want to use the encoder in a mobile app, you have to make it somehow possible for (advanced) users to update/modify the encoder. If you use dynamic linking (the shared library), it's OK. If you use static linking, you have either open source your mobile app or make the object files available somewhere, so users can re-link them.

**Comment by gradha** [comment]
The problem with mobile apps is that you can't modify them or they break their signature and stop working, the only practical solution is to open source the whole app unless an exception is granted for this particular environment. As far as I know everybody willing to use LGPL libraries in iOS/Android is simply ignoring this fact and hoping nobody notices.

**Comment by grendell** [comment]
@gradha while I do not presume to offer legal and/or licensing advice, it's worth noting that it is possible to achieve the shared library requirements described on Android.  If your shared libraries are compressed within the apk, the system will extract and store them in app-private storage.  An "advanced user" with root access could then replace that copy of the library, which the system will load without signature verification.

This is the default behavior until Android Studio 2.2, which will require an explicit flag.  More info [here](https://medium.com/@wkalicinski/smallerapk-part-8-native-libraries-open-from-apk-fc22713861ff#.fpyg0dxje).

**Comment by jonsneyers** [comment]
Are Android and iOS similar in this respect? I thought on Android you can install modified apps if you want (just not via the Google Play Store); iOS is different because it forces you to use the Apple Appstore.

I'm personally OK with you using the encoder in your iOS app (even though it technically violates the terms of the LGPL), as long as you also have the same app on a platform that is not that locked-down (e.g. on Android), so at least theoretically a user can update the library if they want to. I'm not the only copyright holder though (there are others who have contributed code).

Perhaps you should make a statement and only support FLIF on Android, not on iOS :)

Out of curiosity: what kind of app is this? I would expect the decoder to be useful in apps, but the encoder not so much...

**Comment by gradha** [comment]
iOS is completely locked down. Maybe I'm just being paranoid and thinking of the average users and their capability, but it may indeed be possible to repackage an existing Android binary with a different library. Thanks for your comments, I'll investigate first the feasibility of your ideas.

@jonsneyers I'm working on a multimedia communication app where the message exchange involves an image, audio or video. Hence the need to be able to generate the files. Most likely the proposal will be discarded due to iOS requirement.
