### ISSUE TITLE
Native Executables with FLIF 16 release

### ISSUE THREAD

**Issue by TheJaredWilcurt** [FLIF-hub/FLIF#303]
Can we get built native executables for Windows, OSX, and Ubuntu on the [GitHub release page](https://github.com/FLIF-hub/FLIF/releases/tag/v0.2), so people have a trusted source to download.

Most people using image compression CLI's aren't programmers, and lack the environment set up to do builds for themselves. And even for those that do have the appropriate setup, there's no reason to inconvenience every single person that wants to use FLIF when it's a one-time task for the project maintainers.

**Comment by TheJaredWilcurt** [comment]
I built the Windows ones myself:

* https://dl.dropboxusercontent.com/u/1050916/temp/WIN32_FLIF_0.2.0.zip
* https://dl.dropboxusercontent.com/u/1050916/temp/WIN64_FLIF_0.2.0.zip

**Comment by jonsneyers** [comment]
Added your Windows builds to the release page.
