### ISSUE TITLE
Errors in XMP iTXt chunk when converting to PNG format

### ISSUE THREAD

**Issue by boardhead** [FLIF-hub/FLIF#308]
When converting a FLIF containing XMP to a PNG image, the XMP is stored in the PNG image has a number of problems:

1. It is stored as compressed iTXt, but the XMP specification states that it should be uncompressed.
2. There is garbage stored for the iTXt language.
3. There is garbage stored for the iTXt translated keyword.

The following patch fixes these problems:

`diff --git a/src/image/image-png.cpp b/src/image/image-png.cpp
index a47ee48..088e99a 100644
--- a/src/image/image-png.cpp
+++ b/src/image/image-png.cpp
@@ -364,9 +364,11 @@ int image_save_png(const char *filename, const Image &image) {
 #ifdef PNG_iTXt_SUPPORTED
     png_text txt;
     txt.key = (png_charp) "XML:com.adobe.xmp";
-    txt.compression = PNG_ITXT_COMPRESSION_zTXt;
+    txt.compression = PNG_ITXT_COMPRESSION_NONE;
     txt.text_length = 0;
     txt.text = (png_charp) profile;
+    txt.lang = NULL;
+    txt.lang_key = NULL;
     png_set_text(png_ptr, info_ptr, &txt, 1);
 #else
     v_printf(1,"Warning: could not write XMP metadata to PNG file because this version of libpng does not support iTXt.\n");
`

**Comment by bjorn3** [comment]
please put your diif between `<three backticks>diff` and `<three backticks>`

**Comment by boardhead** [comment]
'''diff --git a/src/image/image-png.cpp b/src/image/image-png.cpp
index a47ee48..088e99a 100644
--- a/src/image/image-png.cpp
+++ b/src/image/image-png.cpp
@@ -364,9 +364,11 @@ int image_save_png(const char *filename, const Image &image) {
 #ifdef PNG_iTXt_SUPPORTED
     png_text txt;
     txt.key = (png_charp) "XML:com.adobe.xmp";
-    txt.compression = PNG_ITXT_COMPRESSION_zTXt;
+    txt.compression = PNG_ITXT_COMPRESSION_NONE;
     txt.text_length = 0;
     txt.text = (png_charp) profile;
+    txt.lang = NULL;
+    txt.lang_key = NULL;
     png_set_text(png_ptr, info_ptr, &txt, 1);
 #else
     v_printf(1,"Warning: could not write XMP metadata to PNG file because this version of libpng does not support iTXt.\n");'''

**Comment by boardhead** [comment]
```diff --git a/src/image/image-png.cpp b/src/image/image-png.cpp
index a47ee48..088e99a 100644
--- a/src/image/image-png.cpp
+++ b/src/image/image-png.cpp
@@ -364,9 +364,11 @@ int image_save_png(const char *filename, const Image &image) {
 #ifdef PNG_iTXt_SUPPORTED
     png_text txt;
     txt.key = (png_charp) "XML:com.adobe.xmp";
-    txt.compression = PNG_ITXT_COMPRESSION_zTXt;
+    txt.compression = PNG_ITXT_COMPRESSION_NONE;
     txt.text_length = 0;
     txt.text = (png_charp) profile;
+    txt.lang = NULL;
+    txt.lang_key = NULL;
     png_set_text(png_ptr, info_ptr, &txt, 1);
 #else
     v_printf(1,"Warning: could not write XMP metadata to PNG file because this version of libpng does not support iTXt.\n");```

**Comment by boardhead** [comment]
<three backticks>diff --git a/src/image/image-png.cpp b/src/image/image-png.cpp
index a47ee48..088e99a 100644
--- a/src/image/image-png.cpp
+++ b/src/image/image-png.cpp
@@ -364,9 +364,11 @@ int image_save_png(const char *filename, const Image &image) {
 #ifdef PNG_iTXt_SUPPORTED
     png_text txt;
     txt.key = (png_charp) "XML:com.adobe.xmp";
-    txt.compression = PNG_ITXT_COMPRESSION_zTXt;
+    txt.compression = PNG_ITXT_COMPRESSION_NONE;
     txt.text_length = 0;
     txt.text = (png_charp) profile;
+    txt.lang = NULL;
+    txt.lang_key = NULL;
     png_set_text(png_ptr, info_ptr, &txt, 1);
 #else
     v_printf(1,"Warning: could not write XMP metadata to PNG file because this version of libpng does not support iTXt.\n");<three backticks>

**Comment by boardhead** [comment]
I couldn't get the backticks to work, so here is the patch file.

[flif_png_xmp_patch.txt](https://github.com/FLIF-hub/FLIF/files/524964/flif_png_xmp_patch.txt)

**Comment by jonsneyers** [comment]
Thanks!
