### ISSUE TITLE
static analysis

### ISSUE THREAD

**Issue by necros2k7** [FLIF-hub/FLIF#311]
[raw-tools\sony_arw\arw_encode.c:177]: (portability) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'size_t {aka unsigned long long}'.
[raw-tools\sony_arw\arw_encode.c:140]: (error) Memory leak: buf
[src\viewflif.c:159]: (style) Clarify calculation precedence for '&' and '?'.
[extern\lodepng.cpp:5265]: (style) Condition '!error' is always true
[extern\lodepng.cpp:3057]: (style) C-style pointer casting
[Cppcheck\FLIF-master\src\image\color_range.hpp:42]: (style) Class 'StaticColorRanges' has a constructor with 1 argument that is not explicit.
[Cppcheck\FLIF-master\src\image\color_range.hpp:42]: (performance) Function parameter 'r' should be passed by reference.
[Cppcheck\FLIF-master\src\image\image.hpp:583]: (performance) Variable 'metadata' is assigned in constructor body. Consider performing initialization in initialization list.
[Cppcheck\FLIF-master\src\image\image.hpp:586]: (performance) Variable 'col_begin' is assigned in constructor body. Consider performing initialization in initialization list.
[Cppcheck\FLIF-master\src\image\image.hpp:587]: (performance) Variable 'col_end' is assigned in constructor body. Consider performing initialization in initialization list.
[Cppcheck\FLIF-master\src\image\image.hpp:189]: (performance, inconclusive) Technically the member function 'GeneralPlane::zoom_rowpixelsize' can be static.
[Cppcheck\FLIF-master\src\image\image.hpp:193]: (performance, inconclusive) Technically the member function 'GeneralPlane::zoom_colpixelsize' can be static.

**Comment by jonsneyers** [comment]
Thanks! I'll look into these...
