### ISSUE TITLE
move include at top

### ISSUE THREAD

**Issue by maddin200** [FLIF-hub/FLIF#313]
chance.cpp:
chance.hpp can be the first include

**Comment by jonsneyers** [comment]
Is there a particular reason why the order of the includes matters?

**Comment by maddin200** [comment]
just defensive; so it is guaranteed the include can compile on its own (without hidden includes).

**Comment by maddin200** [comment]
of course minor issue :-)

**Comment by jonsneyers** [comment]
OK, done, thanks :)
