### ISSUE TITLE
getopt licence

### ISSUE THREAD

**Issue by luigino** [FLIF-hub/FLIF#32]
The embedded getopt is licensed under BSD 4-clause, which in my understanding is incompatible with GPL.

Perhaps gnu-getopt would be a better option?

Regards

**Comment by jonsneyers** [comment]
Ugh. Yes, I guess.

**Comment by Lord-Nightmare** [comment]
the getopt in *bsd (notably the one at https://github.com/fanf2/unifdef/blob/master/FreeBSD/getopt.c ) seems to be 3-clause-bsd licensed.

**Comment by Lord-Nightmare** [comment]
There's also @JoakimSoderberg's cargo project: https://github.com/JoakimSoderberg/cargo which is MIT licensed.

**Comment by jonsneyers** [comment]
Can someone plug in the gnu getopt code, check that it compiles in MSVC and make a pull request?
I would do it myself but I haven't used Windows in 20 years...

**Comment by jonsneyers** [comment]
This issue is resolved now (https://github.com/FLIF-hub/FLIF/pull/127)
Thanks, @256bai !

**Comment by r-lyeh** [comment]
FYI, BSD-license & a more modern approach 
https://github.com/weisslj/cpp-argparse

**Comment by r-lyeh** [comment]
Also https://github.com/docopt/docopt.cpp
