### ISSUE TITLE
Option to emit pre-processed lossy image as PPM / PNG

### ISSUE THREAD

**Issue by hrj** [FLIF-hub/FLIF#321]
As a follow up from #320,

> Perhaps a good compromise solution would be to support something like
> flif -Q50 input.ppm lossified.ppm
> i.e. just run the lossy preprocessor and instead of saving the result as a FLIF file, save it as uncompressed pixels. That way, an external tool can efficiently try different amounts of loss, without having to encode and decode a FLIF file every time.

**Comment by jonsneyers** [comment]
Done :)
