### ISSUE TITLE
Unexpected behavior with flif cli tool

### ISSUE THREAD

**Issue by brontosaurusrex** [FLIF-hub/FLIF#323]
Unexpected behavior with `flif *.png` < makes an animation of all the pngs and overwrites the first? png.

**Comment by jonsneyers** [comment]
The behavior is the following: the last file on the command line is assumed to be the output file, so if the `*.png` expands to `1.png 2.png 3.png 4.png` then it'll make an animation of `1.png 2.png 3.png` and save the result to a FLIF file called `4.png`.

I agree that this behavior is probably not what you would expect / desire. So now you'll get a warning if the output FLIF file doesn't have the `.flif` extension, and you'll get an error if the output file already exists.
