### ISSUE TITLE
FLIF on Js?

### ISSUE THREAD

**Issue by mojovski** [FLIF-hub/FLIF#327]
Is there an implementation in javascript? :))

**Comment by lucaswerkmeister** [comment]
https://github.com/UprootLabs/poly-flif

**Comment by mojovski** [comment]
Ahh sorry I need an encoder implementation.

**Comment by hrj** [comment]
@mojovski The FLIF encoder transpiled to JS would likely be very slow. Nevertheless, feel free to raise an issue in poly-flif; I might get around to some time, it if there's enough interest. (I am the lead dev for poly-flif).

**Comment by jonsneyers** [comment]
@hrj: It could be nice to have different variants of the JS, so you can pick what functionality you need: (and have a smaller JS file if you only need some of it)
- full package: encoder + decoder
- encoder only
- decoder only
- still image decoder only
- 8-bit still image decoder only
- 8-bit still image decoder only, no partial loading

I suppose it would be helpful to have some upstream changes to make some of these things compile-time options (some more `#define`s in `config.h`).

For many websites, 8-bit still images without progressive previews is probably a reasonable restriction: you probably only want progressive previews in a native decoder (for performance reasons), and you probably currently only want to use FLIF for below-the-fold images so progressive loading is not that important.
Having those restrictions probably helps quite a bit to make the JS file quite a bit smaller (especially not supporting animations eliminates quite some of the code) and maybe even slightly faster...

**Comment by SaschaNaz** [comment]
I have my own page to support encoding. https://saschanaz.github.io/libflif.js/

**Comment by mojovski** [comment]
Thats awesome! Thanks alot!
@SaschaNaz when I try to open an image (16bit, rgba) using your page, I receive a message:
```
Decoding failed (maybe the format is unsupported by browser): Unspecified error
```
Is there a way to fix this from my side?

@hrj in my case js encoding is interesting since I would like to encode images before sending them to a webserver for further processing (computer vision). This way, the user does not need another heavy software.

Thanks again!

**Comment by SaschaNaz** [comment]
@mojovski I think I assumed input image has 8bit depth for some reason. I will investigate, thanks for reporting.

**Comment by xlz** [comment]
WebAssembly anyone?

**Comment by SaschaNaz** [comment]
Adding WASM=1 will probably generate a valid WebAssembly code but didn't try it yet.

**Comment by hrj** [comment]
I guess this issue can be closed. One implementation is already available https://saschanaz.github.io/libflif.js/

In addition I am planning to support encoding in PolyFLIF soon: https://github.com/UprootLabs/poly-flif/issues/41
