### ISSUE TITLE
flif_info_get_width/height values

### ISSUE THREAD

**Issue by lehitoskin** [FLIF-hub/FLIF#336]
The functions `flif_info_get_width` and `flif_info_get_height` appear to report the incorrect dimensions of a FLIF. I have a flif file that's several thousand pixels wide and several thousand high, but the return values from those functions say 68x71. They seem just so completely unrelated to the image I fed it that I wonder if I used the functions incorrectly.

**Comment by jonsneyers** [comment]
Are you using `flif_read_info_from_memory` first?

These functions are only needed if you don't want to actually decode the file. If you want to know the dimensions of a decoded file, you call `flif_decoder_get_image` and then `flif_image_get_*`.

**Comment by lehitoskin** [comment]
Yes, I run `flif_read_info_from_memory` first and then I run the width and height functions.

**Comment by jonsneyers** [comment]
I can't seem to reproduce the issue. This was the test program I used to test the API:

```
#include <flif.h>
#include <stdio.h>
#include <vector>

int main()
{
    const int TESTSIZE_W = 512;
    const int TESTSIZE_H = 256;
    FLIF_IMAGE* image = flif_create_image(TESTSIZE_W, TESTSIZE_H);
    
    std::vector<uint8_t> row;
    for(int x = 0; x < TESTSIZE_W; ++x)
    {
        row.push_back(x & 255);
        row.push_back(0);
        row.push_back(255 - (x&255));
        row.push_back(255);
    }
    for(int y = 0; y < TESTSIZE_H; ++y)
        flif_image_write_row_RGBA8(image, y, row.data(), row.size());
    
    FLIF_ENCODER* encoder = flif_create_encoder();
    
    flif_encoder_add_image(encoder, image);
    void * buffer;
    size_t size;
    if(!flif_encoder_encode_memory(encoder, &buffer, &size))
    {
        printf("encode failed\n");
        fflush(stdout);
        return 1;
    }
    
    FLIF_INFO* info;
    if(!(info = flif_read_info_from_memory(buffer, size)))
    {
        printf("decode failed\n");
        fflush(stdout);
        return 1;
    }
    uint32_t w = flif_info_get_width(info);
    uint32_t h = flif_info_get_height(info);
        printf("FLIF: %lu bytes; dimensions: %ux%u\n",size,w,h);
    return 0;
}
```

**Comment by lehitoskin** [comment]
I've run your test program and it executes just fine. I wonder what shenanigans are going on with my own code... Ghosts probably. I'll take another look after I've had some sleep.

**Comment by lehitoskin** [comment]
Yeah, I have no idea why my code was messing up, but your example code has been very enlightening. Thanks!
