### ISSUE TITLE
stdin piping has problem on windows

### ISSUE THREAD

**Issue by jeiea** [FLIF-hub/FLIF#341]
From image-pnm.cpp,
```
bool image_load_pnm(const char *filename, Image& image) {
    FILE *fp = NULL;
    if (!strcmp(filename,"-")) fp = stdin;
    else fp = fopen(filename,"rb");
```
Default of `stdin` is text mode on windows, and it regards `1A` byte as EOF.
According to related [stackoverflow post](http://stackoverflow.com/questions/7052896/problems-using-fread-on-stdin-under-win32#comment8432946_7053024), `setmode` can be the solution.
When I discovered this problem, this appeared with crash due to use of array index -1.

**Comment by jonsneyers** [comment]
Thanks for the report! Should be fixed now.

**Comment by jeiea** [comment]
It's not fixed. I've just checked on Win10 RS1.
