### ISSUE TITLE
PNG conversion error

### ISSUE THREAD

**Issue by lehitoskin** [FLIF-hub/FLIF#347]
I have a PNG that has XMP metadata stored in the iTXt chunk, but when I use `flif` to encode, I get this:
`libpng warning: iTXt: incorrect header check`

Now, I got a little scared because I thought my iTXt was improperly formatted, but it's actually because it's compressed. It appears FLIF just doesn't recognize the compression byte is set and inflate the data. It's actually kind of interesting just how many programs that deal with metadata don't recognize compressed iTXt chunks. Running `flif` on a PNG that has XMP metadata that is not compressed does not bring up this error.

**Comment by jonsneyers** [comment]
Is this a problem with flif or with libpng? Are you using a sufficiently recent libpng?

**Comment by lehitoskin** [comment]
Now that is something I'm not certain about. I am using version 1.6.28 of libpng. Is there a way I could check to see if it's my libpng that's acting up instead of FLIF?

**Comment by lehitoskin** [comment]
I grabbed a copy of `pnginfo` and ran it on the same file and that error appeared again. Hm... I I'll have to report this to the libpng people.
