### ISSUE TITLE
API Bug?

### ISSUE THREAD

**Issue by lehitoskin** [FLIF-hub/FLIF#349]
Taking a look at https://github.com/FLIF-hub/FLIF/blob/master/src/library/flif_enc.h#L54 it looks as though `flif_encoder_set_alpha_zero_lossless` should take another argument (according to the comments on the same line), but it currently only takes the one.

**Comment by jonsneyers** [comment]
Added a variant of that function that takes another argument (so you can turn it on and off now). Thanks for noticing this, and sorry it took so long :)
