### ISSUE TITLE
More drive in the Chromium discussion

### ISSUE THREAD

**Issue by RubenKelevra** [FLIF-hub/FLIF#350]
Hey!

I saw you're featuring my bugreport[1] from 2015 in the Chromium bugtracker on your webside - thanks for that!

But I guess we need more drive in the discussion, it would be helpful to keep a active dialog with the developers of Chrom(ium).

Any help for them might be nice as well, I'm not particular helpful on implementing software in C/C++, but I bet you are. :)

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=539120

Best regards

Ruben

**Comment by hrj** [comment]
My prediction:
* FLIF will be adopted first by scientific and industrial users
* FLIF will be then widely used for personal images (mostly by developers and tech-savy users) 
* Eventually it would get popular on the web using JS poly-fills
* It will finally get native support in browsers

Hence, in my opinion, trying to discuss with browser vendors at this early stage is futile. Especially when the browser vendors have their own image standards in the fray.

**Comment by RubenKelevra** [comment]
Possible, but the first response was 'it's not done yet'.

This was proven wrong.

Now they seem to be just unfair for a decision about what file formats they should add to their browser.

Since WebP does not offer a partial download-decoding, it's not a valid competitor. You still have to save two files like with png and jpg to meet a fast and a complete download.

I think FLIF would be nice for example for Wikipedia, all PNGs could be converted and they can offer a fast download of some percentage plus downsizing in the browser to the required size with no additional storage requirement or different files in caching proxies.

Since modern cache proxies support partial cached files, there should be no overhead in the backend.

**Comment by ziemek99** [comment]
FLIF has been superseded by JPEG XL. Due to this fact Chromium bug was closed as WontFix and effort has been moved to the [JPEG XL tracking bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1178058).

You can read more about JPEG XL on an [official website](https://jpeg.org/jpegxl/), [community website](https://jpegxl.info) or dig into [GitHub repository](https://github.com/libjxl/libjxl).
