### ISSUE TITLE
homebrew implementation

### ISSUE THREAD

**Issue by esd100** [FLIF-hub/FLIF#351]
Hi,

I was wondering if there is a newer homebrew implementation than this one (https://github.com/joeyhoer/homebrew-extras/blob/master/flif.rb), which currently retrieves version 0.1.alpha?

Thanks,

Eric

**Comment by lehitoskin** [comment]
Why not create an issue on the repository you linked? Seems like it would be an easy fix.

**Comment by joeyhoer** [comment]
When I attempt to `make install` this, I receive the following error:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: symbols referenced by indirect symbol table entries that can't be stripped in: /usr/local/bin/lib/libflif.dylib
```

Would you like me to open a separate ticket for this?
