### ISSUE TITLE
Metadata question

### ISSUE THREAD

**Issue by lehitoskin** [FLIF-hub/FLIF#352]
In the docs, it says that all non-obligatory chunks have DEFLATE'd contents - does this mean the XMP metadata should be DEFLATE'd before entry via `flif_image_set_metadata` or will the function do that for me?

**Comment by jonsneyers** [comment]
The function does that for you.

**Comment by lehitoskin** [comment]
I wonder if it's more appropriate to put this in another issue, since my first question was answered, but this is also a question about metadata...

Anyway, what's a good way to test if `flif_image_get_metadata` has succeeded? What I mean is running the function on a flif image that does not have metadata has weird results: the length pointer doesn't have a 0 value, but what appears to be the maximum value `size_t` will allow. If I set the length variable to an initial value of 0, then the program crashes with `fish: “./a.out” terminated by signal SIGSEGV (Address boundary error)`

For reference, this is the code I've been using:
```c++
#include <iostream>
#include <flif.h>

int main(void)
{
	// decode the file first
	FLIF_DECODER *decoder = flif_create_decoder();
	std::cout << "Decoding file... ";
	flif_decoder_decode_file(decoder, "002.flif");
	std::cout << "Done!\n";

	// grab the image pointer
	FLIF_IMAGE *image = flif_decoder_get_image(decoder, 0);

	unsigned char **data;
	size_t *length;
	flif_image_get_metadata(image, "eXmp", data, length);

	std::cout << "length: " << *length << std::endl;

	flif_destroy_decoder(decoder);

	return 0;
}

// OUTPUT:
// Decoding file... Done!
// length: 9892260835563793713
```

**Comment by jonsneyers** [comment]
Good question. I think `flif_image_get_metadata` should be changed from a `void` function to one that returns a status, so you can tell if it found that chunk or not.

**Comment by lehitoskin** [comment]
I guess I can close this issue now.
