### ISSUE TITLE
Missing fclose

### ISSUE THREAD

**Issue by maddin200** [FLIF-hub/FLIF#355]
src\image\image-pnm.cpp line 178

missing fclose(fp);

**Comment by waldyrious** [comment]
This will be fixed in [#354](https://github.com/FLIF-hub/FLIF/pull/354/files#diff-2b35122ec7810e32e9a77a266fc2b559).

**Comment by maddin200** [comment]
ok have not seen the patch

**Comment by waldyrious** [comment]
It was an interesting coincidence, though, the PR was opened only a few hours ago :)
