### ISSUE TITLE
Chunk Length Endianness Bug

### ISSUE THREAD

**Issue by lehitoskin** [FLIF-hub/FLIF#359]
I'm looking at a FLIF file that contains XMP metadata in my hex editor and things are looking a little off. It has the chunk name "eXmp" and then two bytes for the length. Now, what my hex editor reports is `0x83 0x01` (33537 in decimal), which is wrong if the numbers are supposed to be in Big Endian order. What I found I needed to do was swap the bytes around for the correct decimal value, but this goes against what the information in the docs say: `An unsigned integer (Big-Endian, MSB first) stored on a variable number of bytes.` Quite confusing, indeed.

If the intent was Big Endian order, then the FLIF functions are doing it wrong. If the intent was for Little Endian order, then the docs are wrong.

**Comment by boardhead** [comment]
Read the specification.  Lengths are stored as a variable-sized integer. 0x83 0x01 is big endian and corresponds to a length 385 bytes (((0x83 & 0x7f) << 7) | 0x01).

- Phil

**Comment by jonsneyers** [comment]
Yes, it's a big-endian variable-sized integer. Confusing in a hex editor, but allows short lengths in 1 or 2 bytes while having no upper bound at all on the maximum length. It's the same encoding as for the image dimensions in the header (I took the idea from the BPG spec).

**Comment by lehitoskin** [comment]
Forgive my ignorance, but wouldn't 0x83 0x01 actually be 387? Plugging 0x0183 into hex converters all come out to be 387.

**Comment by jonsneyers** [comment]
From the work-in-progress spec: (http://flif.info/spec.html)

Variable-size integer encoding (varint):

- An unsigned integer (Big-Endian, MSB first) stored on a variable number of bytes.

- All the bytes except the last one have a '1' as their first bit.

- The unsigned integer is represented as the concatenation of the remaining 7 bit codewords.

So in each byte, the first bit indicates whether it is the last byte or not (1 means "continue", 0 means "done"). Only 7 bits per byte are used for the actual number.

Looking at 0x83 0x01 in binary, we have:

1**0000011**  0**0000001**

which means the actual number is:

0000011  0000001

which in decimal is 385.

**Comment by lehitoskin** [comment]
Ah, I see. Thanks for the explanation!
