### ISSUE TITLE
no long flag for subtract-green

### ISSUE THREAD

**Issue by matthiaskrgr** [FLIF-hub/FLIF#366]
This was added in  27067515df5831fb11a1ea7b1663824db89c4bef .
````flif --verbose --help```` lists
```` -W, --no-subtract-green     disable YCoCg and SubtractGreen transform; use GRB````
it looks like ````flif -W```` works but ````flif --no-subtract-green```` does not.
```` /home/matthias/vcs/github/FLIF/src/flif: unrecognized option '--no-subtract-green' ````.

**Comment by jonsneyers** [comment]
Good catch!
