### ISSUE TITLE
Max OS X dylib symbols can't be stripped

### ISSUE THREAD

**Issue by joeyhoer** [FLIF-hub/FLIF#369]
When I attempt to `make install` this, I receive the following error:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: symbols referenced by indirect symbol table entries that can't be stripped in: /usr/local/bin/lib/libflif.dylib
```

**Comment by gaming-hacker** [comment]
did you get a fix for this?

**Comment by stek29** [comment]
Somehow `install -s` fail on macOS.
The only solution I found for now is to remove `-s` flag and call `strip -x` manually.
Maybe this should be patched in upstream
