### ISSUE TITLE
Astronomy VAMP AVM metadata support for FLIF images

### ISSUE THREAD

**Issue by benepo** [FLIF-hub/FLIF#373]
Feature request:

Add native [VAMP AVM 1.2rc1 metadata](https://www.virtualastronomy.org/avm_metadata.php) support to FLIF to complement the existing Exif and XMP options.  This is a common metadata standard for astronomy images.

**Comment by lehitoskin** [comment]
Should be pretty easy to pull off; you can add basically any kind of metadata to a FLIF. Here's an idea: have the VAMP AVM chunk be called something like `eAvm`.

**Comment by jonsneyers** [comment]
Yes, basically the only thing to do is agree on a chunk name, add it to the list of known chunks so the decoder doesn't produce warnings for it, and then add support for it in the reader/writer functions for metadata (so you can do e.g. `flif -d image.flif metadata.avm` or `flif -e image.ppm metadata.avm image.flif`). Does PNG support this? If so, then you also need to modify the PNG reader/writer to properly load the corresponding PNG chunk.

**Comment by benepo** [comment]
I know TIFF and JPEG are supported (https://www.virtualastronomy.org/avm_metadata.php#7) but I'll check into PNG.  A cursory search on http://astropix.ipac.caltech.edu/browse hasn't resulted in PNG examples...

**Comment by benepo** [comment]
I checked with the AVM maintainers and they said a long time ago PNG had metadata issues but those appear to have been resolved so technically PNG could support it but the [AVM tools](http://avm.ipac.caltech.edu/page/6) may not have been updated to support PNG.

**Comment by hrj** [comment]
The AVM metadata is coded as an extension to [XMP](https://en.wikipedia.org/wiki/Extensible_Metadata_Platform). XMP is designed to be extensible, and is supported by various formats already. In PNGs, it is stored inside an "iTXt" text block with the keyword "XML:com.adobe.xmp", according to the wikipedia page.

Hence, this issue can be generalized to "Supporting XMP in FLIF".

From the AVM mailing list, I found [this tool](https://github.com/astrofrog/pyavm) for adding AVM to PNGs and JPEGs. The author is active on Github so CCing them in: cc @astrofrog

@astrofrog Can you confirm whether FLIF, as an image format, needs to support only XMP, perhaps by standardising on a chunk name. AVM meta-data can then be attached under the same chunk.

**Comment by benepo** [comment]
A little incentive for your effort: https://www.bountysource.com/issues/43152674-astronomy-vamp-avm-metadata-support-for-flif-images

**Comment by hrj** [comment]
My findings so far:
* I downloaded one of the TIFF files from VAMP website with AVM meta data attached.
* Using `tiffinfo` I can see the AVM data encoded as an XML packet inside the TIFF
* Using `convert` from ImageMagick, the TIFF file can be converted to PNG preserving the metadata.
* The converted PNG contains a `zTXT` chunk with a keyword of `xmp`.
* Unfortunately, this is not the standard keyword for `xmp`. It should be `XML:com.adobe.xmp`
* Fortunately, FLIF encoder recognizes both `xmp` and `XML:com.adobe.xmp`. When encoding the PNG file through FLIF, it emits this message: "PNG contains XMP metadata, copying it."
* Unfortunately, after decoding the FLIF file to PNG the metadata is not emitted into the PNG. I am investigating this.
