### ISSUE TITLE
[Bug] Invalid array access when decoding partially

### ISSUE THREAD

**Issue by hrj** [FLIF-hub/FLIF#381]
In [this code](https://github.com/FLIF-hub/FLIF/blob/master/src/flif-dec.cpp#L280), the `zoomlevels[3]` is being set, although in some cases, `zoomlevels.size() == 3`.

I was getting an error in PolyFLIF while decoding [this file](https://hrj.github.io/static/500-500.flif) and traced the error back here.

We can reproduce the error with: `valgrind flif -q 10 500-500.flif xyz.png`

I can circumvent the error by adding an if condition:
```
      if (zoomlevels.size() > 3) {
        zoomlevels[3] = zoomlevels[1];
      }
``` 

But I am not sure what the right solution is. Should it be something like:

```
    for (i = 0; i < zoomlevels.size(); i++) {
      if (i != 1) {
        zoomlevels[i] = zooomlevels[1];
      }
    }
```

**Comment by jonsneyers** [comment]
Either solution is fine. If the image has a palette, then there should be either 3 or 4 planes.
