### ISSUE TITLE
Animation guide

### ISSUE THREAD

**Issue by benepo** [FLIF-hub/FLIF#395]
Although the FLIF site prominently notes support for animation, there is no explanation on http://flif.info/animation.html for how to actually create an animated FLIF image.  I found the answer at https://github.com/FLIF-hub/FLIF/blob/33122c6f93421dc0bc450a947888103c88ce072b/doc/flif.1#L339 and created one via ```flif -F1000 alpha.png omega.png one-second-animation.flif``` but you may want to add that more prominently on the animation page.

P.S. Is there a way to append a PNG or FLIF image to an existing animated FLIF image?  For example, if I have 5 images and I create a FLIF animated image called example.flif, could I add a sixth image later as an appended frame in the sequence with something like ```flif example.flif image6.png example.flif```?

P.P.S. Is there a Windows desktop viewer that supports animation?  XnView only shows the first frame.

**Comment by lehitoskin** [comment]
P.S.
AFAICT it should work exactly like that. Something along the lines of `flif -F1000 a.png b.flif c.png out.flif` should work.

P.P.S.
The `viewflif` utility that's provided will probably work on Windows, but I confess I've never tried it myself. Alternatively, there's Ivy, which is in the list of related projects, though I haven't made a release lately so it's a little out of date.

**Comment by hrj** [comment]
> P.S. Is there a way to append a PNG or FLIF image to an existing animated FLIF image? For example, if I have 5 images and I create a FLIF animated image called example.flif, could I add a sixth image later as an appended frame in the sequence with something like flif example.flif image6.png example.flif?

No, that doesn't work right now. It would require re-encoding all the frames, atleast for some types of FLIF files. I am not sure if @jonsneyers would want to add support for that in the reference encoder, but you can create a separate issue to track it; the need for documentation is a good topic by itself.

**Comment by jonsneyers** [comment]
FLIF never stores animations as a sequence of frames, they are always interlaced in some way. Either only by channel (when using `-N`), or by channel and zoomlevel (when using `-I`). In the first case, what is stored (assuming YCoCg) is first a sequence of grayscale frames, then two sequences of chroma frames. In the second case, you get progressive previews of the entire animation very early.

But I suppose we could modify the encoder to take input frames also in FLIF format, and if those FLIF files contain multiple frames they just contribute more than one frame to the final animation. That shouldn't be too hard to add. But the encode effort will be the same as for encoding the entire animation from scratch, there is no way around that.

**Comment by benepo** [comment]
That makes sense, now that I consider the progressive decoding capability.  Thanks!
