### ISSUE TITLE
Expose a real library interface

### ISSUE THREAD

**Issue by dwbuiten** [FLIF-hub/FLIF#4]
`flif.h` needs some love:
- function prefixes (`encode` and `decode` pollute the global namespace with generic names)
- C interface (C++ has no fixed ABI, and every language under the sun uses a C FFI for bindings.)
- Don't define v_printf in a public header.

**Comment by Wiladams** [comment]
I would agree with these comments as well.
I'd have flif_encode, flif_decode, at the very least.
Also, if you could use 'C' for the public interface, I'd love it as a LuaJIT binding, for example, would take about 2 seconds.

Not sure why v_printf is in there.  It's not a real problem, but I'm not sure you need it in that public interface.
If you can make these couple of small changes, I'm sure the scripting world will love it.  Of course, it is a GPL freely available code, so there's nothing stopping anyone from forking and going on about their business, but it would be nice if it were provided from the source.

**Comment by fherzog2** [comment]
I thought about it, this could be the interface. The encoder stuff is still missing. And I'm not so sure about which format the image should be extract to. I guess YIQA would be possible too.
Any suggestions?

```
#ifndef FLIF_INTERFACE_H
#define FLIF_INTERFACE_H

/*!
* C interface for the FLIF library
*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

    struct FLIF_IMAGE;
    struct FLIF_DECODER;
    
    uint32_t __stdcall flif_image_get_width(FLIF_IMAGE* image);
    uint32_t __stdcall flif_image_get_height(FLIF_IMAGE* image);
    void __stdcall flif_image_extract_rgba_row(FLIF_IMAGE* image, uint32_t row, void* buffer, size_t buffer_size_bytes);

    FLIF_DECODER* __stdcall flif_create_file_decoder();
    void __stdcall flif_destroy_decoder(FLIF_DECODER* decoder);
    
    void __stdcall flif_decoder_set_quality(FLIF_DECODER* decoder, int32_t quality);
    void __stdcall flif_decoder_set_scale(FLIF_DECODER* decoder, uint32_t scale);
    int32_t __stdcall flif_decoder_decode_file(FLIF_DECODER* decoder, char* filename);
    size_t __stdcall flif_decoder_num_images(FLIF_DECODER* decoder);
    FLIF_IMAGE* __stdcall flif_decoder_get_image(FLIF_DECODER* decoder, size_t index);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif // FLIF_INTERFACE_H
```

**Comment by dwbuiten** [comment]
A few notes:
    - `__stdcall` is windows-only.
    - Where's the encoder?
    - How to you decode/encode to a buffer (i.e. not a file)?

**Comment by fherzog2** [comment]
Thanks, your suggestion have been taken into account.
```
#ifndef FLIF_INTERFACE_H
#define FLIF_INTERFACE_H

/*!
* C interface for the FLIF library
*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

    struct FLIF_IMAGE;
    struct FLIF_DECODER;
    struct FLIF_ENCODER;
    
    #define FLIF_API __cdecl
    
    FLIF_IMAGE* FLIF_API flif_create_image(uint32_t width, uint32_t height);
    void FLIF_API flif_destroy_image(FLIF_IMAGE* image);
    
    uint32_t FLIF_API flif_image_get_width(FLIF_IMAGE* image);
    uint32_t FLIF_API flif_image_get_height(FLIF_IMAGE* image);
    void FLIF_API flif_image_write_row_RGBA8(FLIF_IMAGE* image, uint32_t row, void* buffer, size_t buffer_size_bytes);
    void FLIF_API flif_image_read_row_RGBA8(FLIF_IMAGE* image, uint32_t row, void* buffer, size_t buffer_size_bytes);

    FLIF_DECODER* FLIF_API flif_create_file_decoder();
    void FLIF_API flif_destroy_decoder(FLIF_DECODER* decoder);
    
    void FLIF_API flif_decoder_set_quality(FLIF_DECODER* decoder, int32_t quality);
    void FLIF_API flif_decoder_set_scale(FLIF_DECODER* decoder, uint32_t scale);
    
    int32_t FLIF_API flif_decoder_decode_file(FLIF_DECODER* decoder, char* filename);
    int32_t FLIF_API flif_decoder_decode_memory(FLIF_DECODER* decoder, void* buffer, size_t buffer_size_bytes);
    size_t FLIF_API flif_decoder_num_images(FLIF_DECODER* decoder);
    FLIF_IMAGE* FLIF_API flif_decoder_get_image(FLIF_DECODER* decoder, size_t index);
    
    FLIF_ENCODER* FLIF_API flif_create_encoder();
    void FLIF_API flif_destroy_encoder(FLIF_ENCODER* encoder);
    
    void FLIF_API flif_encoder_set_interlaced(FLIF_ENCODER* encoder, uin32_t interlaced);
    void FLIF_API flif_encoder_set_learn_repeat(FLIF_ENCODER* encoder, uin32_t repeats);
    void FLIF_API flif_encoder_set_auto_color_buckets(FLIF_ENCODER* encoder, uin32_t acb);
    void FLIF_API flif_encoder_set_frame_delay(FLIF_ENCODER* encoder, uin32_t delay);
    void FLIF_API flif_encoder_set_palette_size(FLIF_ENCODER* encoder, in32_t size);
    void FLIF_API flif_encoder_set_loopback(FLIF_ENCODER* encoder, in32_t loopback);
    
    void FLIF_API flif_encoder_add_image(FLIF_ENCODER* encoder, FLIF_IMAGE* image);
    int32_t FLIF_API flif_encoder_encode_file(FLIF_ENCODER* encoder, char* filename);
    int32_t FLIF_API flif_encoder_encode_memory(FLIF_ENCODER* encoder, void** buffer, size_t* buffer_size_bytes);
    
    // freeing the memory received from flif_encoder_encode_memory() 
    void FLIF_API flif_free_memory(void* buffer);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif // FLIF_INTERFACE_H
```


The usage would look like this.
```
FLIF_IMAGE* image = flif_create_image(64, 64);
if(image)
{
    uint8_t buffer[64*4];
    memset(buffer, 255, sizeof(buffer));
    for(uint32_t r = 0; r < 64; ++r)
       flif_image_write_row_RGBA8(image, r, buffer, sizeof(buffer));

    FLIF_ENCODER* encoder = flif_create_encoder();
    if(encoder)
    {
        flif_encoder_add_image(encoder, image);
        flif_encoder_encode_file(encoder, "test.flif");

        flif_destroy_encoder(encoder);
    }

    FLIF_DECODER* decoder = flif_create_decoder();
    if(decoder)
    {
        if(flif_decoder_decode_file(decoder, "test.flif") != 0)
        {
            FLIF_IMAGE* image2 = flif_decoder_get_image(decoder, 0);
            // do something with the image
        }
        
        flif_destroy_decoder(decoder);
    }

    flif_destroy_image(image);
}
```

**Comment by Two-Scoops** [comment]
perhaps some general init functions as well?
`void FLIF_API flif_decoder_init(FLIF_DECODER* decoder, int32_t quality, uint32_t scale);`
`void FLIF_API flif_encoder_init(FLIF_ENCODER* encoder, uint32_t interlaced, uint32_t learn_repeats, uint32_t acb, uint32_t frame_delay, int32_t palette_size, int32_t loopback);`

We could also look towards other libraries such as libpng or zlib for possible API styles to build off of.

**Comment by fherzog2** [comment]
I don't think having a big init function is wise. What if more parameters are added to the encode/decode functions? Then we would have to change the signature of `flif_decoder_init`. Having a setter function for each parameter keeps the API more stable even in case of changes.

Also, the proposed interface is basically just a thin wrapper for the C++ classes FLIF_IMAGE, FLIF_DECODER and FLIF_ENCODER, which will be added as well. Since flif is using C++ under the hood, in contrast to libpng, I think this kind of interface makes sense.

I tried to keep best practices for library interfaces in mind, e.g.
- using opaque pointers for structs
- setter functions for the private data of the structs
- no global state hidden in the library
- memory allocated by the library should be freed by the library as well

The only I'm not sure about is how to read and write pixels of the image. For now there are function to the get 8 bit RGBA, which works, but it doesn't seem nice. Maybe the format could be given as an argument:
`void FLIF_API flif_image_read_row(FLIF_IMAGE* image, uint32_t row, FLIF_PIXEL_FORMAT format, void* buffer, size_t buffer_size_bytes);`

**Comment by Wiladams** [comment]
That looks like a good enough start.  I'd put it on the library and give it a chance to iterate for real.  I'll be writing a LuaJIT binding for it, and this looks good enough for that purpose.

**Comment by hrj** [comment]
​Couldn't you define a `config​` structure that bundles together all config
parameters? The structure would then be passed as a parameter to the
encoder / decoder (different structures for encoder / decoder if required).

If a new config option gets added, it doesn't need a new parameter nor a
new function to be added to the API; only the structure gets updated.

**Comment by fherzog2** [comment]
@Wiladams You're right, and I'm almost ready to commit.

@hrj I thought about this too. If you have a public config structure, the user has to make sure that he sets all the parameters correctly, instead of just the one he wants to change.

Also, this is about compatibility. Consider the following:
- program is linked with libflif
- libflif gets an update, increasing the size of the config struct
- program does not get updated
- program is still using the old API, allocates a struct that is too small and passes it too libflif
- libflif accesses a part of the stack that it shouldn't

With setter functions we don't have this problem. libpng has also moved away from public structs.

**Comment by hrj** [comment]
On Mon, Oct 19, 2015 at 11:35 AM, fherzog2 <notifications@github.com> wrote:

> If you have a public config structure, the user has to make sure that he
> sets all the parameters correctly, instead of just the one he wants to
> change.
>
Could be solved with an API called `initConfig`.​


program is still using the old API, allocates a struct that is too small
> and passes it too libflif


​Yup, this would be a problem. I thought this would be a problem with
functions too, but now realise that PIC + dynamic linking solves it.

**Comment by Wiladams** [comment]
I would stick to the hidden structure method.  If you expose these internal structures, you'll then have to do some form of versioning, either introducing a 'size' field, or an explicit 'version', which then makes it an opaque mess anyway.

Most of the modern APIs are taking the hidden structure approach, as well as 'ref/unref' for memory management.

**Comment by dwbuiten** [comment]
> That looks like a good enough start. I'd put it on the library and give it a chance to iterate for real. I'll be writing a LuaJIT binding for it, and this looks good enough for that purpose.

Just don'y break ABI/API too much :smile:

I also agree with hidden structs. It's the easiest way to keep the ABI stable (So functions don't rely on sizes of structs at compile time).

**Comment by Two-Scoops** [comment]
@fherzog2 Ah yes, that would make more sense. I don't have too much experience with API design, I was just thinking about code verbosity (not a huge deal in retrospect). If anyone really wanted to, they could just have an init macro.

**Comment by jonsneyers** [comment]
OK, the API is still far from final, but I think there has been enough progress to close this issue now.
Any problems / suggestions related to libflif can be discussed in new issues if needed.
