### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by stek29** [FLIF-hub/FLIF#401]
More than 100 commits were made to master since latest release, including 1a606d9.
Without it building on macOS requires a patch, which prevents FLIF from being added to Homebrew.

So, are there any plans on making (at least minor) release anytime soon?

**Comment by hrj** [comment]
I don't know what the release process is, but I would request holding out for a couple of days, while I optimise things around the preview code. The API has changed during the optimisation process, and might change again.

**Comment by stek29** [comment]
I don't know it either, that's why I opened this issue -- it's a <kbd>discussion</kbd>

**Comment by jonsneyers** [comment]
Let's tag a release soonish – let's call it 0.3-rc1 (release candidate 1) for now. We can release it as 0.3 when we feel the API is stable enough for that. But I agree that it's time to tag a release.

**Comment by stek29** [comment]
Thank you :D
