### ISSUE TITLE
Setting first callback quality as 10000 does not give decode_over=true

### ISSUE THREAD

**Issue by SaschaNaz** [FLIF-hub/FLIF#411]
It seems high value for first callback quality causes decode_over value never be true.

**Comment by SaschaNaz** [comment]
4000 also caused this issue for my Lenna.flif, not sure for other images.

**Comment by hrj** [comment]
@SaschaNaz Can you create a branch with your exact callback logic added to viewflif, so that I can test it?

It is worth checking the returned integer from your callback. If the value is smaller than current progress level (or some such condition), the callback function is never invoked again.

**Comment by SaschaNaz** [comment]
The callback itself is being invoked correctly, it just gives quality=10000, decode_over=0. It seems `progressive_qual_shown` value becomes 10000 and this causes the issue.

**Comment by SaschaNaz** [comment]
Fixing the lines to `progressive_qual_target = issue_callback(callback, user_data, qual, io.ftell(), qual == 10000, populatePartialImages);` resolves this issue but not sure this is the proper fix.

What if decoder just issued a callback with quality Q<10000, tries reading the next data but it was inexistent, so decoder wants to send decode_over=true but the progressive_qual_shown is already Q?

**Comment by hrj** [comment]
@SaschaNaz Are you able to reproduce this with viewflif? If yes, a patch or branch would be useful for debugging.

**Comment by SaschaNaz** [comment]
Sorry for the delay, hopefully I can repro this on viewflif today...

**Comment by hrj** [comment]
@SaschaNaz I had created a utility for debugging progressive decodes called [dumpflif](https://gist.github.com/hrj/6d11eb4c2061636e018bbd12f26ff153). It's a simplified version of viewflif, with no UI. You could use that for reproducing the bug.

**Comment by SaschaNaz** [comment]
@hji Thanks! It looks much simpler :smile:

**Comment by SaschaNaz** [comment]
I added some lines on viewflif.c https://github.com/SaschaNaz/FLIF/commit/091b115ecd6b10cca26cf810c8b925ab1638937f and got strange result:

```
Decoding progressively...
Decode is not over, got quality: 546
Decode is not over, got quality: 1927
Decode is not over, got quality: 3854
Decode is not over, got quality: 5208
Decode is not over, got quality: 6875
Decode is not over, got quality: 8333
Decode is not over, got quality: 10000
```

`decode_over` is now never being `true`. Am I doing something wrong here?

**Comment by hrj** [comment]
@SaschaNaz I am seeing the same results.

The `decode_over` is `true` only when a callback is issued after the end of decoding. Note also that, if a callback has been already issued at `quality==10000` as part of the inner decoding loop, then it is not issued again.

We can probably tweak this logic, such that `quality==10000` callback is never issued in the inner decoding loop. In which case, the callback for `quality==10000 && decode_over==true` will be issued at the end of decoding.

**Comment by SaschaNaz** [comment]
>What if decoder just issued a callback with quality Q<10000, tries reading the next data but it was inexistent, so decoder wants to send a new callback with (quality=Q, decode_over=true), but the progressive_qual_shown is already Q because of previous callback?

It seems my previous concern was not valid. If decoder fails on quality Q on a broken file it issues a callback with decode_over=true or false, if it is true then no issue, if not the quality target will be updated by the return value (>Q) and then it will issue another callback with decode_over=true.

I thought the solution should be slightly more complex, but it seems it shouldn't be. :smile: Filed #431 to fix this.
