### ISSUE TITLE
Keeping transparent pixels when using the API

### ISSUE THREAD

**Issue by spillerrec** [FLIF-hub/FLIF#424]
I wan't to try using FLIF instead of WebP for one of my projects, but it stores special information in transparent pixels used when overlaying two images. However I cannot find out how to get it stop using the default behavior of only being visual lossless. (Which I personally find terrifying, as I expect lossless formats not to modify my data.)

I have tried to call `flif_encoder_set_alpha_zero_lossless` but that does not appear to do anything. #349 might be related.

Test image:
![transparent-noise](https://cloud.githubusercontent.com/assets/2292170/26169387/af742e2e-3b3d-11e7-9f73-448649226c51.png)
Test image end. Ends up being 20 bytes when using the API, instead of 617 KiB with `-K`.

**Comment by jonsneyers** [comment]
You have to set the option before calling flif_encoder_add_image, maybe that is the problem?

**Comment by spillerrec** [comment]
I'm calling it right after `flif_create_encoder`. Call order of all FLIF functions:

1. `flif_create_encoder()`
2. `flif_encoder_set_alpha_zero_lossless( encoder );`
3. `flif_create_image( width, height ) `
4. `flif_image_write_row_RGBA8` * y
5. `flif_encoder_add_image`
6. `flif_destroy_image`
7. `flif_encoder_encode_memory`
8. `flif_destroy_encoder`
