### ISSUE TITLE
Comparison HEIF and FLIF

### ISSUE THREAD

**Issue by proyb6** [FLIF-hub/FLIF#439]
I have not seen any comparison between the two formats, are there plans to compare?

**Comment by jonsneyers** [comment]
HEIF is just like BPG, HEVC intra frame in a container. So the comparison has already been done; there is no substantial difference between HEIF and BPG in terms of image compression. (The HEIF container is much more advanced/complicated, but that just means there is slightly more container overhead for simple images).

**Comment by DonaldTsang** [comment]
@jonsneyers so HEIF, as a container for x264 would get better support?
