### ISSUE TITLE
Missing targets in Makefile

### ISSUE THREAD

**Issue by williain** [FLIF-hub/FLIF#452]
The Readme describes some makefile pseudo targets:

> 
>     make flif to build just the flif command line tool
>     make libflif.so to build the LGPL'ed shared library
>     make libflif_dec.so to build the Apache licensed decode-only shared library
>     make viewflif to build the example viewer (it depends on the decode library)
> 
Of these, only the flif target is in the makefile.  This could be trivially fixed by editing the readme, or if these pseudo targets are considered a good thing, the makefile could be patched.  Up to you :)

**Comment by grendell** [comment]
Per the line above those you quoted:
>Navigate to the FLIF/src directory

The Makefile in src has all of these targets. I believe the top-level Makefile is meant solely for installing FLIF, as described in the next section.

**Comment by williain** [comment]
Ah, so it does.  Thanks for clearing that up!
