### ISSUE TITLE
Process for reporting security bugs?

### ISSUE THREAD

**Issue by Google-Autofuzz** [FLIF-hub/FLIF#455]
Hello FLIF team,

As part of our fuzzing efforts at Google, we are interested in understanding the process for reporting potential security issues to your project in a private manner. Could you please advise us if there is a private tracker for these kinds of bugs, or if you prefer them filed in a publicly visible way?

Thanks!

**Comment by hrj** [comment]
We don't have a separate issues tracker for security issues. Please join and post to https://gitter.im/FLIF-hub/security.

If that is not possible, I suggest filing publicly.
