### ISSUE TITLE
chromium-support for FLIF

### ISSUE THREAD

**Issue by RubenKelevra** [FLIF-hub/FLIF#475]
I've opened another discussion about FLIF-support in Chrom*, since the last one was basically ignored in the last year.

https://bugs.chromium.org/p/chromium/issues/detail?id=793683

Please consider to engage yourself again in this discussion, to help opening a more deeply dialog about the future of FLIF in Chrom*.

Best regards

Ruben

**Comment by ziemek99** [comment]
Duplicate of #350, additionally FLIF has been superseded by JPEG XL. More info under the [original issue](https://github.com/FLIF-hub/FLIF/issues/350#issuecomment-974822250). Closing.
