### ISSUE TITLE
Do you have contacts in Discord?

### ISSUE THREAD

**Issue by DonaldTsang** [FLIF-hub/FLIF#481]
It would be great if you have a Discord account for me to contact you.
There are some imageboard projects that only communicates in Discord/IRC.

**Comment by hrj** [comment]
There is currently no Discord account.
I didn't understand your last statement.

Is it a problem that you can't share images in gitter? If so, you could join us in the Matrix room: `#gitter_FLIF-hub=2FFLIF:matrix.org`. Matrix clients allow easy sharing of images in the room.

**Comment by DonaldTsang** [comment]
@hrj when I say "There are some imageboard projects that only communicates in Discord/IRC." I meant that there are software projects that would benefit from FLIF that are on Discord only

**Comment by ziemek99** [comment]
FLIF has been superseded by JPEG XL. You can read more about JPEG XL on an [official website](https://jpeg.org/jpegxl/), [community website](https://jpegxl.info) or dig into [GitHub repository](https://github.com/libjxl/libjxl).

And to answer the question: yes, you can now contact Jon, other JPEG XL devs and the community on a [Discord server](https://discord.gg/DqkQgDRTFu).
