### ISSUE TITLE
--resize=WxH not working as expected.

### ISSUE THREAD

**Issue by TheJaredWilcurt** [FLIF-hub/FLIF#488]
![catrun01](https://user-images.githubusercontent.com/4629794/35781973-1a9e3ba4-09bf-11e8-9690-8cd7a4b320a3.png)

This 80x64 image cannot be resized to 1x1, 8x6, or 800x640. All fail. using `--resize=1x1` or `-r1x1`. I was not able to get any success attempts.

![kodim01](https://user-images.githubusercontent.com/4629794/35781976-2acf5eea-09bf-11e8-8020-2c72d4430f51.png)

This 768x512 image cannot be resized to 800x600, but when set to 80x60 it outputs at 48x32.

My expectation would be that whatever values are put in would be what the image would be resized to exactly. If only passing in one value, it should use that as the width and resize proportionally (if we want that feature, I don't think it's really needed).

**Comment by jonsneyers** [comment]
The relevant documentation is here:
https://github.com/FLIF-hub/FLIF/blob/master/doc/flif.1#L123

The `--resize` option is meant for getting a partial decode, which means you will get the original resolution divided by 2^N for some value of N. It will only work for interlaced FLIFs (i.e. encoded with the `-I` option, which is the default for large enough images). You will get something that is smaller than the resolution you specify.

You can use the option `--fit WxH` to do what you want. Basically it will do a `--resize` to a suitable (higher) resolution, and then do a simple downscale to get it to the exact dimensions you want. You can specify just the width too. It will also work for non-interlaced FLIF files.

Note however that proper scaling (and certainly upscaling) is beyond the scope of the FLIF decoder; you will get best results by doing a `--resize` to dimensions that are larger than the actual canvas you need to fill, then downscale yourself from there using Lanczos or whatever proper downscaling filter you prefer.  You need to decode the full image for best quality, and say 3x the canvas size for good quality, 2x canvas size for OK quality. If you specify 2x the canvas size, depending on the actual numbers, you will get something between 1x and 2x the pixels.
