### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by paride** [FLIF-hub/FLIF#495]
@jonsneyers This is just to let you know that I'm working on the Debian packaging for FLIF, and I took the ownership of the RFP bug #812761, making it an ITP.

If you are fine with it I can report here any difficulty encountered during the packaging work that could be solved by minor upstream changes.

**Comment by jonsneyers** [comment]
Nice! Thanks!

**Comment by paride** [comment]
@jonsneyers flif is now in the Debian queue for new packages.

I had to patch `src/Makefile` in order to build the package with all the build flags I wanted. I submitted a PR for this: #497.

Another minor issue is that `viewflif` doesn't have a manpage. Do you plan to write one at some point?

If you are not using the `debian/` directory, I suggest dropping it. It creates a bit of confusion. See:

https://wiki.debian.org/DebianMentorsFaq#What.27s_wrong_with_upstream_shipping_a_debian.2F_directory.3F

**Comment by jonsneyers** [comment]
Cool!

In my opinion, `viewflif` is not really suitable for distribution - it is just a small, unpolished demo application to show how libflif can be used to progressively load an image or animation, but I think it has some issues (I think it segfaults or has race conditions in some cases). 

Sorry about the confusion created by the `debian/` directory. I will remove it.

**Comment by paride** [comment]
Thanks for merging the Makefile patch. About viewflif, we are now distributing it in Debian (it's not available yet, but the package has just been accepted). If you really think it should not let me know and I'll pull it. It is packages separately from the flif-tools and from the library.

**Comment by paride** [comment]
FLIF is now in Debian. An outstanding issue remains open: #498.
