### ISSUE TITLE
How can i use this format?

### ISSUE THREAD

**Issue by shilpi230** [FLIF-hub/FLIF#50]
Any instructions of how to install it on Mac OS X. I already have libpng package in it how can install flip format ? Any example of conversion will also be helpful. :)

**Comment by TheFox** [comment]
1. `git clone git@github.com:jonsneyers/FLIF.git`
2. `cd FLIF`
3. `make`
4. ?
5. Profit with `./flif -h` ;)

**Comment by jmank88** [comment]
If you don't want to muddle with dependencies and are familiar with Docker, I put together a Dockerfile here: https://github.com/jmank88/docker/tree/master/flif

**Comment by szborows** [comment]
@jmank88 maybe it would be meaningful to pull the Dockerfile into FLIF repo?

**Comment by jmank88** [comment]
Sounds good to me, if it doesn't clutter things up too much.
I think there was some talk on another thread suggesting moving to a FLIF org with a few different repos (WebDemo, C++, Rust, GoLang). That might make things a bit more organized and manageable. Would be up to @jonsneyers though.
Otherwise I'd be happy to move the Dockerfile wherever the community thinks is most logical.

**Comment by shilpi230** [comment]
Hey @TheFox thank you for answering but pardon me what is ```?``` this

**Comment by shilpi230** [comment]
Otherwise thank u i got it working :D amazing job :clap:

**Comment by sipa** [comment]
Shilpi: I think the answer to your question is "You don't." This is not a
finalized image format, there is no polished implementation for it, and
nothing supports it yet. It is way too experimental at this point to "use"
it in any conventional meaning of the word. The software here is just for
developers to play with and demonstrate the usefulness of the format.

**Comment by shilpi230** [comment]
Yes i understand @sipa i am also a developer working in same area thats why.. i just wanted to play around with it and its really useful :) Thank you again :)
