### ISSUE TITLE
Loss data when compress transparent PNG.

### ISSUE THREAD

**Issue by KujiKita** [FLIF-hub/FLIF#500]
The problem is that FLIF ignores the color information if the transparency is zero. This is a problem, because I need the original color information even where the transparency is zero. So I think this is a problem, because FLIF loses this data when compressed. Of course there is an option to store separately the Alpha channel and RGB, but these are crutches.

1.png - Screenshot of channels in img01_calculated_final.png.
2.png - Screenshot of channels in img01_calculated_final.flif.png.

![1](https://user-images.githubusercontent.com/16868747/39405004-caf06f36-4ba5-11e8-91d5-75c70723bbbe.png)
![2](https://user-images.githubusercontent.com/16868747/39405005-cb18706c-4ba5-11e8-990a-bb2243f69d0b.png)

![img01_calculated_final](https://user-images.githubusercontent.com/16868747/39405029-d95630ba-4ba5-11e8-996d-b548fb7b4e7e.png)
![img01_calculated_final flif](https://user-images.githubusercontent.com/16868747/39405030-d97a0bfc-4ba5-11e8-940b-555ebeaf68e2.png)

**Comment by weltkante** [comment]
FLIF has an option `flif_encoder_set_alpha_zero_lossless` for turning off this optimization if you are going to use the alpha channel for something else than the standard blending formula. If you aren't coding directly against the library but using a tool it probably has a switch for that (if not thats a bug in the tool).

**Comment by KujiKita** [comment]
Oh. I see. This is option -K. I just don't understand for what it needs. Issue closed.

**Comment by MartBlur** [comment]
I think you might have forgotten to close the issue.
