### ISSUE TITLE
Update website: irfanview plugin now supports FLIF

### ISSUE THREAD

**Issue by daT4v1s** [FLIF-hub/FLIF#530]
https://www.irfanview.com/main_history.htm 
![Screenshot from 2019-03-09 18-32-40](https://user-images.githubusercontent.com/47403824/54079054-63528b80-42a2-11e9-90ff-70cdddc4291b.png)

https://flif.info/software.html as of 2019-03mar-09
![Screenshot from 2019-03-09 19-31-11](https://user-images.githubusercontent.com/47403824/54079055-6a799980-42a2-11e9-8bd1-5b0a6d3e1778.png)

**Comment by ziemek99** [comment]
Fixed by FLIF-hub/FLIF-hub.github.io#20.
