### ISSUE TITLE
Create a FLIF file with a 256 color palette.

### ISSUE THREAD

**Issue by QLaHPD** [FLIF-hub/FLIF#555]
How to create a FLIF file with a 256 color palette, where the input file will be a PNG with a 256 color (8 bit) palette? 
I tried to use the "--keep-palette" option, but the output file is always in RGBA format (32 bits).

**Comment by bjorn3** [comment]
https://github.com/FLIF-hub/FLIF/pull/554

> FLIF development has stopped since FLIF is superceded by FUIF and then again by JPEG XL (https://jpeg.org/jpegxl/index.html), which is based on a combination of Pik and FUIF.
A royalty-free and open source reference implementation of JPEG XL is available on [GitLab](https://gitlab.com/wg1/jpeg-xl).

**Comment by QLaHPD** [comment]
So does this mean that in the latest version of FLIF it is not possible to use these settings?

**Comment by bjorn3** [comment]
I don't now if the decoder can create PNG's with 256 color palette. FLIF itself should support color palette's though.

**Comment by QLaHPD** [comment]
Do you know if there is a way to set the bit depth in the current implementation (in the encoder)?

**Comment by bjorn3** [comment]
I think the encoder just takes the bit depth of the input image.
