### ISSUE TITLE
FLIF decoder needs to be afl-fuzzed (crashes found)

### ISSUE THREAD

**Issue by d33tah** [FLIF-hub/FLIF#57]
I ran a quick round of fuzzing using [American Fuzzy Lop](http://lcamtuf.coredump.cx/afl/) and immediately found the following examples:

```
root@e0a3ba7ea8a2:~/FLIF-master# ./flif -d  o/crashes/id\:000001*  /tmp/a.png
Warning: expected file name extension ".flif" for input file, trying anyway...
Floating point exception (core dumped)
root@e0a3ba7ea8a2:~/FLIF-master# base64 o/crashes/id\:000001\,sig\:08\,src\:000000\,op\:flip1\,pos\:7 
RkxJRjMxAAAAHoHz280HVfdJ5npjXrviUtU3tQFYKJtBFQorvILr
root@e0a3ba7ea8a2:~/FLIF-master# ./flif -d  o/crashes/id\:000002*  /tmp/a.png
Warning: expected file name extension ".flif" for input file, trying anyway...
Invalid tree. Aborting tree decoding.
Invalid tree. Aborting tree decoding.
Invalid tree. Aborting tree decoding.
Segmentation fault (core dumped)
root@e0a3ba7ea8a2:~/FLIF-master# ./flif -d  o/crashes/id\:000003*  /tmp/a.png
Warning: expected file name extension ".flif" for input file, trying anyway...
Invalid tree. Aborting tree decoding.
Invalid tree. Aborting tree decoding.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
root@e0a3ba7ea8a2:~/FLIF-master# ./flif -d  o/crashes/id\:000004*  /tmp/a.png
Warning: expected file name extension ".flif" for input file, trying anyway...
Segmentation fault (core dumped)
root@e0a3ba7ea8a2:~/FLIF-master# ./flif -d  o/crashes/id\:000005*  /tmp/a.png
Warning: expected file name extension ".flif" for input file, trying anyway...
Invalid tree. Aborting tree decoding.
Segmentation fault (core dumped)
root@e0a3ba7ea8a2:~/FLIF-master# ./flif -d  o/crashes/id\:000006*  /tmp/a.png
Warning: expected file name extension ".flif" for input file, trying anyway...
Invalid tree. Aborting tree decoding.
Invalid tree. Aborting tree decoding.
Invalid tree. Aborting tree decoding.
*** Error in `./flif': free(): invalid next size (fast): 0x0000000000d88760 ***
Aborted (core dumped)
root@e0a3ba7ea8a2:~/FLIF-master# ./flif -d  o/crashes/id\:000007*  /tmp/a.png
Warning: expected file name extension ".flif" for input file, trying anyway...
*** Error in `./flif': free(): invalid next size (fast): 0x00000000027111b0 ***
Aborted (core dumped)
root@e0a3ba7ea8a2:~/FLIF-master# ./flif -d  o/crashes/id\:000008*  /tmp/a.png
Warning: expected file name extension ".flif" for input file, trying anyway...
Floating point exception (core dumped)
root@e0a3ba7ea8a2:~/FLIF-master# ./flif -d  o/crashes/id\:000009*  /tmp/a.png
Warning: expected file name extension ".flif" for input file, trying anyway...
Invalid tree. Aborting tree decoding.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

You can quickly reproduce the fuzzing by creating a file named Dockerfile in a separate directory. File should have the following contents:

```
FROM d33tah/afl-sid
RUN cd /; wget --no-check-certificate "https://github.com/jonsneyers/FLIF/archive/master.zip"
RUN apt-get update; apt-get install pkg-config libpng-dev unzip -y
RUN . ~/.bashrc; cd / ; unzip master.zip ; cd FLIF-master ; make -j`nproc` 
RUN mkdir /i ; echo 'RkxJRjMxAAEAHoHz280HVfdJ5npjXrviUtU3tQFYKJtBFQorvILr' | base64 -d > /i/1
CMD . ~/.bashrc; afl-fuzz -i /i -o /FLIF-master/o /FLIF-master/flif -d @@ /tmp/out.png
```

Then `cd` into this file and run: `sudo docker build -t flif-afl-sid . && sudo docker run -ti flif-afl-sid`. Let me know if you need help extracting the crashing files later.

**Comment by jonsneyers** [comment]
Very good point.

**Comment by d33tah** [comment]
@FLIF-hub: are you planning to do the fuzzing? I believe that this kind of work should be done by the core developers that know how to maximize the test case coverage.

**Comment by d33tah** [comment]
I'd be happy to guide you though.

**Comment by d33tah** [comment]
@FLIF-hub: here are results of five hours of fuzzing with just one trivial test case: http://kolos.math.uni.lodz.pl/~d33tah/flif.tar.gz - you're probably mostly interested in o/*/crashes directories. If you need more information, take a look at "7) Interpreting output" there: https://github.com/d33tah/afl-fuzz-releases/blob/master/docs/README

**Comment by jonsneyers** [comment]
Downloaded. Will not have time anytime soon to look at it though.

**Comment by jonsneyers** [comment]
Does anyone want to do some more fuzzing or is it robust enough for now? Wondering if this issue can be closed...

**Comment by d33tah** [comment]
I'd suppose that the core developers of a project would know best how to come up with use cases that maximize code coverage. Have you tried running afl-fuzz on your own?

**Comment by d33tah** [comment]
I ran the Dockerfile I posted here and within a minute it found 14 unfixed crashes. I wouldn't say that this is issue is ready for closing.

**Comment by jonsneyers** [comment]
Well the thing is, I can only use afl-fuzz in "dumb" mode here, because the instrumented mode only works on x86 hardware.
Most of the "crashes" I can find were flif exiting with a nonzero status because it detected that the mutated input file was invalid. So that's not a crash, that's the desired behavior, no?

**Comment by d33tah** [comment]
AFL detects a crash when you're getting a signal like SIGABRT, SIGFPE or SIGSEGV, which is usually a sign of a serious problem - quite likely one related to security. Non-zero exit code is called a normal execution flow. As for x86 only - instead of afl-gcc, you can try afl-llvm-fast, which works on all platforms.

In other words - crash detection is decent and can detect very serious bugs and non-x86 archs are supported as well, so I still believe that it's very important to run extensive fuzzing. Let me know if you need any further help.

**Comment by jonsneyers** [comment]
Oh, you're right, nonzero exit code does not cause the crash, it was the artificial memory limit of 25MB that caused the crash. If I set the memory limit higher, they disappear. The memory limit can easily be broken by mutating the header to specify that the image resolution is huge.

**Comment by d33tah** [comment]
This would count as one crash only though. AFL would find it and look for others - headers with a memory limit that doesn't crash. I usually compile my programs with ASAN support though and then run them in a separate Docker instance with `-m none` - ASAN on 64 bit needs to see all the memory space, but does wonders detecting non-crashing memory errors.

**Comment by matthiaskrgr** [comment]
You can also combine address sanitizer and undefined behaviour sanitizer,
-fsanitize=address,undefined -fno-omit-frame-pointer -g3

**Comment by jonsneyers** [comment]
OK, the low hanging fuzzing fruits are found now, I think.
Unless anyone else finds some more, I'm going to close this issue (a new one can of course be opened when vulnerabilities are found).

**Comment by d33tah** [comment]
Sounds good. :) Did you take a look at code coverage of the input files from the output_dir/queue directory? Could you publish the input and output files so that others could continue from that point?

**Comment by jonsneyers** [comment]
In case anyone wants to continue fuzzing:

As input files, you can just use one or more small images and small animations (e.g. greyscale, RGB and RGBA) and encode those with various encoder settings, in particular `-ia`, `-na`, `-ib`, `-nb`. `-R`, `-C` for still images and those plus `-l0`, `-l1`, `-l100`, `-F`.
I don't think the exact input matters much, because simple bitflips in the header will quickly produce corrupt images with all kinds of encoder settings.

**Comment by d33tah** [comment]
@jonsneyers:

It found one crash when I tried it today. The updated Dockerfile is:

```
FROM d33tah/afl-sid
RUN apt-get update; apt-get install pkg-config libpng-dev unzip libsdl2-dev -y
RUN cd /; wget --no-check-certificate "https://github.com/jonsneyers/FLIF/archive/master.zip"
RUN . ~/.bashrc; cd / ; unzip master.zip ; cd FLIF-master ; make -j`nproc` 
RUN mkdir /i ; echo 'RkxJRjMxAAEAHoHz280HVfdJ5npjXrviUtU3tQFYKJtBFQorvILr' | base64 -d > /i/1
CMD . ~/.bashrc; afl-fuzz -i /i -o /FLIF-master/o /FLIF-master/src/flif -d @@ /tmp/out.png
```
