### ISSUE TITLE
Could not read input file

### ISSUE THREAD

**Issue by N00D13** [FLIF-hub/FLIF#62]
I try to use```./flif -i test.png test.flif``` but every time i got 
```Could not read input file: test.png```.
Whats my fault?

**Comment by jonsneyers** [comment]
Can anyone duplicate this?

**Comment by N00D13** [comment]
Information: I use Mac OSX  10.11

**Comment by jonsneyers** [comment]
are you compiling without libpng and trying to encode a >8 bit image?

**Comment by jonsneyers** [comment]
OK, I'm going to assume this is a build issue and not an actual problem.
