### ISSUE TITLE
alpha reference data in a separate plane

### ISSUE THREAD

**Issue by hrj** [FLIF-hub/FLIF#67]
Notes from chat:

> sipa: @jonsneyer @hrj In the pyani example animation, with 70% or more truncation, you see weird transparent circular lines in the decoded image. My guess is that these are the result from interpolating incomplete Alpha data, in between "deep alpha" negative values, and positive ones?
> I think it's better to have this reference data in a separate plane, which perhaps allows better prediction (as it's not really correlated to the actual alpha data), perhaps even a plane which goes before Y?
> jonsneyer: Yes. Good idea. FRA was just a quick hack, it can be improved...

**Comment by jonsneyers** [comment]
Labeling this as bug because it ruins the progressive decoding if we don't do this.

**Comment by jonsneyers** [comment]
Working on this...
