### ISSUE TITLE
image.h: Assertion `max<256' failed.

### ISSUE THREAD

**Issue by matthiaskrgr** [FLIF-hub/FLIF#72]
There is an assertion failure while converting this file:
https://gitlab.com/freedroid/freedroid-src/raw/72d74df09a18bfc2dee8c92a17b43beb55da17d2/graphics/droids/arthur/portrait.png

flif: /home/matthias/vcs/github/FLIF/image/image.h:139: void Image::init(uint32_t, uint32_t, ColorVal, ColorVal, int): Assertion `max<256' failed.
zsh: abort (core dumped)  /home/matthias/vcs/github/FLIF/flif ./graphics/droids/arthur/portrait.png 

edit: I didn't pass any extra options to flif, just  "flif oldfile newfile"

**Comment by jonsneyers** [comment]
That's because it's a PNG with 16bit per color, and you need to compile FLIF with the flag SUPPORT_HDR in config.h if you want it to be able to deal with > 8 bit per channel.
(Maybe that flag should be there by default, or at least the error-handling should improve)
