### ISSUE TITLE
Why have both lossless and lossy compression in the same image format?

### ISSUE THREAD

**Issue by PaintNinja** [FLIF-hub/FLIF#79]
Please forgive me if this is obvious, but why are modern video and image codecs/formats opting to have both lossy and lossless compression under the same file extension?

I see it as a disadvantage to do this, as it would make it harder to find a lossless version. Imagine if all FLACs could be either lossy or lossless, but you never knew until you downloaded it - wouldn't that be a waste of time?

Do you have plans on having a different file extension for lossy FLIFs than lossless FLIFs?

**Comment by sipa** [comment]
FLIF doesn't support lossy at all.

It does support partial decoding, where a truncated file can be decoded to
obtain a lower resolution version of the same file, though.

**Comment by PaintNinja** [comment]
Ah, ok. I saw however that you have plans to include lossy encoding in the future (as found on flif.info)? Why if you can already do lossy decoding?

**Comment by sipa** [comment]
Lossy encoding is intended to look good at low size. Truncated lossless
files will decode to something that has much worse quality than a file that
was intended to be only that size.

The use case is very different: partial decoding gives you a decent preview
while you're loading the data still, but it's not intended to be used for
just that.

**Comment by PaintNinja** [comment]
Do you plan on making lossy encoded FLIF files have a different file extension so that they can be easily differentiated from lossless FLIF files?

**Comment by jonsneyers** [comment]
Lossy FLIF is not high on my priority list, it is a can of worms.

 If it would have the same extension, then the header would say it is lossy. But you can never be sure that something is lossless -- you can always quantize or downsample and then save that 'losslessly'.

**Comment by PaintNinja** [comment]
Thanks for helping me understand this.

By the way, great work with your format so far! I tried encoding a screenshot from PNG format and FLIF was roughly half the size!

I'm looking forward to seeing further progress in FLIF and wish you and your contributors the best of luck. :)
