### ISSUE TITLE
Decode quality percentage

### ISSUE THREAD

**Issue by objectDisorientedProgrammer** [FLIF-hub/FLIF#96]
FLIF allows the quality flag to take the value -1.
Typing: ```./flif -q -1 ~/Pictures/out.flif ~/Pictures/decode-1.png```
does **not** give the error message that other negative values do: ```Not a sensible number for option -q```

It gives the same output as if you chose 0% (see files). The first one is 0%, the second -1%, and the last is the original.

![decode0](https://cloud.githubusercontent.com/assets/2829762/10556780/7c90eadc-7443-11e5-934f-426d674aea75.png)
![decode-1](https://cloud.githubusercontent.com/assets/2829762/10556781/7c931d70-7443-11e5-8f34-d8ef8cfc3279.png)
![original](https://cloud.githubusercontent.com/assets/2829762/10556782/7c936f82-7443-11e5-9927-75aa31279e2d.png)

**Comment by jonsneyers** [comment]
Right. This is something historical that is no longer relevant. So it should indeed be removed.
