### ISSUE TITLE
Avoid 64 bit arithmetic in performance-critical parts if possible

### ISSUE THREAD

**Issue by jonsneyers** [FLIF-hub/FLIF#97]

**Comment by sipa** [comment]
This may help asm.js and ARM systems in particular. In x86_64 there is
little performance difference between 32 and 64 arithmetic, unless using
SSE.

**Comment by jonsneyers** [comment]
@sipa : Some time ago you said: "if we'd have a 20-bit range coder instead of 24-bit, we could do all coding without uint64_t
we need to multiply the 24-bit range variable with the 16-bit chance variable, which temporarily gives a 40-bit result
but the chance only has 12 significant bits"

I'm having some trouble going from a 24 to a 20 bit rac: simply setting `MAX_RANGE_BITS = 20` in `maniac/rac.hpp` does not seem to work. Could you give it a try? I expect little compression performance difference (after all, moving from 40 to 24 bits had no effect).

**Comment by msm595** [comment]
I don't know enough about how RAC works, but after playing around with it a bit, it seems like it only works when `MIN_RANGE_BITS` winds up being a full number of bytes (8, 16, 24, 32 bits). If you set `MAX_RANGE_BITS = 20` and `MIN_RANGE_BITS = 16`, it works. Setting `MIN_RANGE_BITS = 8` does not work however.

There may be consequences of the difference in range only being 4 bits now though.

**Comment by jonsneyers** [comment]
Setting `MIN_RANGE_BITS = 16` essentially causes the range to be 24 bits regardless of what `MAX_RANGE_BITS` is set to, so it works, but it doesn't help to eliminate the 64-bit arithmetic.
It indeed looks like the code assumes things to be an integer number of bytes.

**Comment by jonsneyers** [comment]
Is there any 64-bit arithmetic left now in the _decoder_ ? As far as I know, the decoder doesn't use 64-bit arithmetic in any performance-critical spot now. The encoder still uses some 64-bit numbers to maintain virtual sizes and running property averages while constructing MANIAC trees, but that could be changed (if you want an encoder that is more friendly to 32-bit machines) without changing the format stream.
